export interface DailyPaper {
  date: string; // ISO YYYY-MM-DD
  title: string;
  titleZh?: string;
  authors: string;
  arxivId: string;
  tags: string[];
  /** One-line why it matters — English */
  why: string;
  /** One-line why it matters — Chinese */
  whyZh: string;
  /** Is this editor's pick */
  pick?: boolean;
  /** Has full deep-dive */
  slug?: string;
}

export const dailyPapers: DailyPaper[] = [
  {
    date: "2026-04-17",
    title: "From P(y|x) to P(y): Investigating Reinforcement Learning in Pre-train Space",
    titleZh: "从P(y|x)到P(y)：在预训练空间探索强化学习",
    authors: "Yuqiao Tan et al.",
    arxivId: "2604.14142",
    tags: ["Reasoning", "RLHF", "Pre-training"],
    why: "DSRL: NSR in pre-train space expands reasoning horizon, then standard RL fine-tunes — outperforms all strong RLVR baselines.",
    whyZh: "PreRL在预训练空间扩展推理边界，NSR快速剪枝错误路径，DSRL全面超越强基线。",
    pick: true,
  },
  {
    date: "2026-04-17",
    title: "LongCoT: Benchmarking Long-Horizon Chain-of-Thought Reasoning",
    titleZh: "LongCoT：长时域思维链推理基准评测",
    authors: "Sumeet Ramesh Motwani et al.",
    arxivId: "2604.14140",
    tags: ["Reasoning", "Benchmark"],
    why: "2,500 expert problems requiring up to 100K reasoning tokens — best frontier models score <10%, exposing a major long-horizon gap.",
    whyZh: "2500道专家题需推理10万token，最优模型不足10%，长链推理缺口巨大。",
  },
  {
    date: "2026-04-17",
    title: "Calibration-Aware Policy Optimization for Reasoning LLMs",
    titleZh: "面向推理LLM的校准感知策略优化",
    authors: "Ziqi Wang et al.",
    arxivId: "2604.12632",
    tags: ["Reasoning", "RLHF"],
    why: "CAPO fixes GRPO's overconfidence via logistic AUC surrogate loss — jointly optimizes calibration and accuracy. ACL 2026.",
    whyZh: "CAPO通过AUC替代损失修正GRPO过度自信，同时优化准确率与不确定性校准，ACL 2026录用。",
  },
  {
    date: "2026-04-14",
    title: "SPPO: Sequence-Level PPO for Long-Horizon Reasoning Tasks",
    titleZh: "SPPO：面向长时域推理任务的序列级PPO",
    authors: "Tianyi Wang et al.",
    arxivId: "2604.08865",
    tags: ["Reasoning", "RLHF"],
    why: "Reformulates PPO as sequence-level contextual bandit — no value model needed, matches GRPO-style methods with far lower memory cost.",
    whyZh: "将PPO重构为序列级语境赌博机，无需价值模型，以更低内存成本匹配GRPO类方法性能。",
    pick: true,
  },
  {
    date: "2026-04-14",
    title: "RAGEN-2: Reasoning Collapse in Agentic RL",
    titleZh: "RAGEN-2：智能体强化学习中的推理坍塌",
    authors: "Zihan Wang et al.",
    arxivId: "2604.06268",
    tags: ["Reasoning", "Agent"],
    why: "Discovers template collapse — a failure mode invisible to entropy in agentic RL — fixed with SNR-aware prompt filtering.",
    whyZh: "发现模板坍塌这一被熵指标忽视的推理失效模式，提出信噪比滤波策略有效缓解。",
  },
  {
    date: "2026-04-14",
    title: "DFlash: Block Diffusion for Flash Speculative Decoding",
    titleZh: "DFlash：面向快速推测解码的块扩散方法",
    authors: "Jian Chen et al.",
    arxivId: "2602.06036",
    tags: ["Diffusion LM", "Efficient Inference"],
    why: "Block diffusion drafter achieves 6x lossless speedup over base LLM — 2.5x faster than EAGLE-3 with no quality loss.",
    whyZh: "用块扩散模型作为推测解码草稿器，实现6倍无损加速，比EAGLE-3快2.5倍。",
  },
  {
    date: "2026-04-11",
    title: "SUPERNOVA: Eliciting General Reasoning in LLMs with Reinforcement Learning on Natural Instructions",
    titleZh: "SUPERNOVA：利用自然指令强化学习激发LLM通用推理能力",
    authors: "Ashima Suvarna et al.",
    arxivId: "2604.08477",
    tags: ["Reasoning", "RLHF"],
    why: "Mines natural instruction datasets for verifiable rewards — extends RLVR beyond math/code to causal, temporal, and abductive reasoning without hand-crafted reward functions.",
    whyZh: "从自然指令数据集中挖掘可验证奖励，将RLVR扩展至因果、时序和溯因推理，无需手工设计奖励函数。",
    pick: true,
  },
  {
    date: "2026-04-12",
    title: "TriAttention: Efficient Long Reasoning with Trigonometric KV Compression",
    titleZh: "TriAttention：基于三角函数KV压缩的高效长推理",
    authors: "Weian Mao et al.",
    arxivId: "2604.04921",
    tags: ["Efficient Inference", "Reasoning"],
    why: "Trigonometric KV compression matches full-attention accuracy at 2.5x throughput or 10.7x memory reduction — practical long-reasoning speedup from MIT/NVIDIA.",
    whyZh: "三角函数KV压缩在保持全注意力精度的同时实现2.5倍吞吐或10.7倍内存压缩，大幅提升长推理效率。",
    pick: true,
  },
  {
    date: "2026-04-13",
    title: "DFlash: Block Diffusion for Flash Speculative Decoding",
    titleZh: "DFlash：用于闪速投机解码的块扩散模型",
    authors: "Jian Chen et al.",
    arxivId: "2602.06036",
    tags: ["Diffusion LM", "Efficient Inference"],
    why: "Block diffusion as speculative draft model achieves 6x LLM inference speedup — bridges diffusion language models and fast autoregressive deployment.",
    whyZh: "以块扩散模型为投机解码草稿器实现6倍推理加速，将扩散LM与高速自回归部署相连接。",
  },
  {
    date: "2026-04-13",
    title: "Fast-dVLM: Efficient Block-Diffusion VLM via Direct Conversion from Autoregressive VLM",
    titleZh: "Fast-dVLM：从自回归VLM直接转换的高效块扩散视觉语言模型",
    authors: "Chengyue Wu et al.",
    arxivId: "2604.06832",
    tags: ["Diffusion LM", "Multimodal"],
    why: "Direct AR-to-diffusion VLM conversion with KV-cache-compatible parallel decoding — matches AR quality across 11 multimodal benchmarks at lower inference cost.",
    whyZh: "直接将自回归VLM转换为块扩散模型，支持KV缓存并行解码，在11项多模态基准上匹配AR质量。",
  },
  {
    date: "2026-04-12",
    title: "Multi-objective Evolutionary Merging Enables Efficient Reasoning Models",
    titleZh: "多目标进化模型合并实现高效推理",
    authors: "Mario Iacobelli et al.",
    arxivId: "2604.06465",
    tags: ["Reasoning", "Efficient Inference"],
    why: "Evolutionary merging of reasoning and base models eliminates overthinking — cuts inference cost on easy problems without sacrificing accuracy.",
    whyZh: "进化合并推理模型与基础模型，消除过度思考，简单问题推理开销显著降低。",
  },
  {
    date: "2026-04-12",
    title: "OptiMer: Optimal Distribution Vector Merging Is Better than Data Mixing for Continual Pre-Training",
    titleZh: "OptiMer：分布向量合并优于数据混合的持续预训练方法",
    authors: "Haiyue Song et al.",
    arxivId: "2603.28858",
    tags: ["Pre-training"],
    why: "Trains one model per dataset then merges distribution vectors with Bayesian-optimized weights — beats data-mixing CPT on Gemma 3 27B with 15–35x lower search cost.",
    whyZh: "每个数据集单独训练后合并分布向量，贝叶斯优化权重，在Gemma 3 27B上超越数据混合，搜索成本降低15-35倍。",
    pick: true,
  },
  {
    date: "2026-04-12",
    title: "DyMoE: Dynamic Expert Orchestration with Mixed-Precision Quantization for Efficient MoE Inference on Edge",
    titleZh: "DyMoE：面向边缘设备高效MoE推理的动态专家编排与混合精度量化",
    authors: "Yuegui Huang et al.",
    arxivId: "2603.19172",
    tags: ["MoE", "Quantization", "Efficient Inference"],
    why: "Importance-aware dynamic quantization + look-ahead prefetching for MoE on commodity edge hardware — 3.4–22.7x TTFT speedup without accuracy loss.",
    whyZh: "通过重要性感知动态量化和预取，在商用边缘硬件上实现MoE推理，首次令牌延迟降低3.4-22.7倍，精度无损。",
  },
  {
    date: "2026-04-12",
    title: "Verify Before You Commit: Towards Faithful Reasoning in LLM Agents via Self-Auditing",
    titleZh: "执行前验证：基于自我审计的LLM智能体忠实推理",
    authors: "Wenhao Yuan et al.",
    arxivId: "2604.08401",
    tags: ["Agent", "Reasoning"],
    why: "SAVeR adversarially audits internal belief states before action commitment — stops unsupported beliefs from cascading across memory and decision steps in long-horizon agents. ACL 2026.",
    whyZh: "SAVeR在执行前对内部信念状态进行对抗性审计，阻止错误信念在长程智能体记忆和决策中级联传播，ACL 2026录用。",
  },
  {
    date: "2026-04-12",
    title: "Single-Agent LLMs Outperform Multi-Agent Systems on Multi-Hop Reasoning Under Equal Thinking Token Budgets",
    titleZh: "等量Token预算下单智能体LLM在多跳推理上超越多智能体系统",
    authors: "Dat Tran et al.",
    arxivId: "2604.02460",
    tags: ["Agent", "Reasoning", "Theory"],
    why: "Information-theoretic proof via Data Processing Inequality: single-agent LLMs are more token-efficient on multi-hop reasoning — reported MAS gains trace to uncontrolled compute.",
    whyZh: "通过数据处理不等式证明单智能体在多跳推理上信息效率更高，多智能体系统的性能优势源于未受控的计算量差异。",
  },
  {
    date: "2026-04-11",
    title: "Dynin-Omni: Omnimodal Unified Large Diffusion Language Model",
    titleZh: "Dynin-Omni：统一全模态大型扩散语言模型",
    authors: "Dynin AI et al.",
    arxivId: "2604.00007",
    tags: ["Diffusion LM", "Multimodal"],
    why: "First masked-diffusion omnimodal model unifying text, image, speech, and video — achieves strong results across 19 multimodal benchmarks.",
    whyZh: "首个掩码扩散全模态基础模型，统一文本、图像、语音与视频，19项基准表现强劲。",
  },
  {
    date: "2026-04-11",
    title: "Fast-dVLM: Efficient Block-Diffusion VLM via Direct Conversion from Autoregressive VLM",
    titleZh: "Fast-dVLM：从自回归VLM直接转换的高效块扩散视觉语言模型",
    authors: "Fast-dVLM Team et al.",
    arxivId: "2604.06832",
    tags: ["Diffusion LM", "Efficient Inference", "Vision"],
    why: "Converts AR VLMs to block-diffusion with KV-cache-compatible parallel decoding — brings diffusion inference speedups to vision-language models.",
    whyZh: "将自回归VLM转换为块扩散模型，支持KV缓存并行解码，将扩散推理加速能力引入视觉语言模型。",
  },
  {
    date: "2026-04-11",
    title: "Learning from the Right Rollouts: Data Attribution for PPO-based LLM Post-Training",
    titleZh: "从正确轨迹中学习：基于PPO的LLM后训练数据归因",
    authors: "I-PPO Team et al.",
    arxivId: "2604.01597",
    tags: ["RLHF", "Fine-tuning"],
    why: "I-PPO uses gradient-based influence scores to filter RL rollouts — reduces unfaithful CoT reasoning and accelerates PPO post-training.",
    whyZh: "I-PPO通过梯度影响分数过滤RL轨迹，减少不忠实CoT推理，加速PPO后训练收敛。",
  },
  {
    date: "2026-04-10",
    title: "SHAPE: Stage-aware Hierarchical Advantage via Potential Estimation for LLM Reasoning",
    titleZh: "SHAPE：面向LLM推理的阶段感知层级优势估计",
    authors: "Zhengyang Ai et al.",
    arxivId: "2604.06636",
    tags: ["Reasoning", "RLHF"],
    why: "Formalizes reasoning as state-space trajectories with hierarchical credit assignment — +3% accuracy and 30% fewer tokens by distinguishing efficient breakthroughs from mere verbosity.",
    whyZh: "将推理形式化为状态空间轨迹并引入层级信用分配，准确率提升3%、token减少30%，有效区分有效突破与冗余推理。",
    pick: true,
  },
  {
    date: "2026-04-10",
    title: "DARE: Diffusion Large Language Models Alignment and Reinforcement Executor",
    titleZh: "DARE：扩散大语言模型对齐与强化执行框架",
    authors: "Jingyi Yang et al.",
    arxivId: "2604.04215",
    tags: ["Diffusion LM", "Alignment", "RLHF"],
    why: "First unified open framework for post-training diffusion LLMs — brings RLHF and alignment tooling to both masked and block diffusion models, accelerating reproducible research.",
    whyZh: "首个统一的扩散LLM后训练开源框架，为掩码和块扩散模型提供RLHF与对齐工具，推动可复现研究。",
    pick: true,
  },
  {
    date: "2026-04-10",
    title: "LightThinker++: From Reasoning Compression to Memory Management",
    titleZh: "LightThinker++：从推理压缩到内存管理",
    authors: "Yuqi Zhu et al.",
    arxivId: "2604.03679",
    tags: ["Reasoning", "Efficient Inference"],
    why: "Upgrades LightThinker with explicit adaptive memory primitives — 70% peak token reduction and 26% faster inference by scheduling purposeful memory actions in long reasoning chains.",
    whyZh: "通过显式自适应内存原语升级LightThinker，峰值token减少70%、推理加速26%，适用于长推理链。",
    pick: true,
  },
  {
    date: "2026-04-10",
    title: "Rethinking Token Prediction: Tree-Structured Diffusion Language Model",
    titleZh: "重新思考Token预测：树结构扩散语言模型",
    authors: "Zihao Wu et al.",
    arxivId: "2604.03537",
    tags: ["Diffusion LM", "Theory"],
    why: "Exploits vocabulary hierarchy in masked diffusion — models intermediate latent states as ancestor nodes in a pre-built tree, enabling more structured and efficient training.",
    whyZh: "在掩码扩散中利用词汇层次结构，将中间潜在状态建模为词汇树祖先节点，训练更结构化高效。",
  },
  {
    date: "2026-04-10",
    title: "Dependency-Guided Parallel Decoding in Discrete Diffusion Language Models",
    titleZh: "离散扩散语言模型中的依赖引导并行解码",
    authors: "Liran Ringel et al.",
    arxivId: "2604.02560",
    tags: ["Diffusion LM", "Efficient Inference"],
    why: "DEMASK predictor estimates pairwise token dependencies to guide safe parallel unmasking — fixes quality degradation from distributional mismatch in discrete diffusion decoding.",
    whyZh: "DEMASK预测token间依赖关系，安全选择可并行解码的位置，解决离散扩散中分布不匹配导致的质量下降。",
  },
  {
    date: "2026-04-10",
    title: "MSA: Memory Sparse Attention for Efficient End-to-End Memory Model Scaling to 100M Tokens",
    titleZh: "MSA：面向1亿Token高效端到端记忆模型的稀疏注意力",
    authors: "EverMind AI",
    arxivId: "2603.23516",
    tags: ["Efficient Inference", "Pre-training"],
    why: "Scalable sparse attention + document-wise RoPE achieves near-linear complexity at 100M tokens — only 9% quality degradation vs 16K baseline, beating SOTA RAG and memory agents.",
    whyZh: "通过可扩展稀疏注意力和文档级RoPE实现1亿token近线性复杂度，相比16K基线仅降级9%，超越SOTA RAG系统。",
  },
  {
    date: "2025-02-14",
    title: "Large Language Diffusion Models (LLaDA)",
    titleZh: "大语言扩散模型 (LLaDA)",
    authors: "Nie et al.",
    arxivId: "2502.09992",
    tags: ["Diffusion LM", "Pre-training"],
    why: "First diffusion LM at 8B scale that matches LLaMA3 — proves AR is not the only path to powerful LLMs.",
    whyZh: "首个 8B 规模扩散语言模型，可与 LLaMA3 媲美 — 证明 AR 不是强大 LLM 的唯一路径。",
    pick: true,
    slug: "llada",
  },
  {
    date: "2025-02-28",
    title: "Block Diffusion: Interpolating Between Autoregressive and Diffusion Language Models",
    titleZh: "Block Diffusion: 在自回归与扩散语言模型之间插值",
    authors: "Arriola et al.",
    arxivId: "2503.09573",
    tags: ["Diffusion LM", "Efficient Inference"],
    why: "Elegant bridge between AR and diffusion — block size B lets you tune the speed/quality tradeoff continuously.",
    whyZh: "AR 和扩散之间的优雅桥梁 — 块大小 B 让你连续调节速度/质量权衡。",
    pick: true,
    slug: "block-diffusion",
  },
  {
    date: "2025-05-28",
    title: "Fast-dLLM: Training-free Acceleration of Diffusion LLM",
    authors: "Wu et al.",
    arxivId: "2505.22618",
    tags: ["Diffusion LM", "Efficient Inference"],
    why: "Practical 3-10x speedup for masked diffusion LMs with no retraining — makes diffusion LMs viable for production.",
    whyZh: "无需重新训练即可实现 3-10 倍加速 — 让扩散语言模型可用于生产环境。",
    pick: true,
    slug: "fast-dllm",
  },
  {
    date: "2024-06-11",
    title: "Simple and Effective Masked Diffusion Language Models (MDLM)",
    authors: "Sahoo et al.",
    arxivId: "2406.07524",
    tags: ["Diffusion LM", "Theory"],
    why: "Clean theoretical foundation for masked diffusion — derives the training loss from first principles, no hand-tuning.",
    whyZh: "掩码扩散的简洁理论基础 — 从基本原理推导训练损失，无需手动调整。",
    slug: "mdlm",
  },
  {
    date: "2023-05-29",
    title: "Direct Preference Optimization (DPO)",
    authors: "Rafailov et al.",
    arxivId: "2305.18290",
    tags: ["Alignment", "RLHF"],
    why: "Killed the reward model — rewrites RLHF as a simple binary loss. Became the default fine-tuning method for open-source LLMs.",
    whyZh: "消灭了奖励模型 — 将 RLHF 改写为简单的二元损失。成为开源 LLM 的默认微调方法。",
    pick: true,
    slug: "dpo",
  },
  {
    date: "2024-02-05",
    title: "DeepSeekMath: Pushing the Limits of Mathematical Reasoning (GRPO)",
    authors: "Shao et al.",
    arxivId: "2402.03300",
    tags: ["RL", "Math Reasoning"],
    why: "Introduces GRPO — removes the critic network from PPO by using group-relative rewards. Powers DeepSeek-R1.",
    whyZh: "引入 GRPO — 通过组相对奖励从 PPO 中移除 critic 网络。为 DeepSeek-R1 提供动力。",
    slug: "grpo",
  },
  {
    date: "2025-01-22",
    title: "DeepSeek-R1: Incentivizing Reasoning Capability in LLMs via RL",
    authors: "DeepSeek AI",
    arxivId: "2501.12948",
    tags: ["RL", "Reasoning", "Chain-of-Thought"],
    why: "Matches o1 on math/code using pure RL with GRPO — no supervised CoT data needed. Huge open-source release.",
    whyZh: "仅使用 GRPO 强化学习在数学/代码上匹配 o1 — 不需要监督 CoT 数据。重要的开源发布。",
    pick: true,
  },
  {
    date: "2017-06-12",
    title: "Attention Is All You Need",
    authors: "Vaswani et al.",
    arxivId: "1706.03762",
    tags: ["Transformer", "Architecture"],
    why: "The paper that started it all — replaced RNNs with attention. Everything in this repo builds on it.",
    whyZh: "一切的起点 — 用注意力替代 RNN。本站所有论文都建立在它之上。",
    slug: "attention-is-all-you-need",
  },
];

export const allTags = Array.from(
  new Set(dailyPapers.flatMap((p) => p.tags))
).sort();
