export interface DailyPaper {
  date: string; // ISO YYYY-MM-DD
  title: string;
  titleZh?: string;
  authors: string;
  arxivId: string;
  tags: string[];
  /** One-line why it matters — English */
  why: string;
  /** One-line why it matters — Chinese */
  whyZh: string;
  /** Is this editor's pick */
  pick?: boolean;
  /** Has full deep-dive */
  slug?: string;
}

export const dailyPapers: DailyPaper[] = [
  {
    date: "2026-04-11",
    title: "SUPERNOVA: Eliciting General Reasoning in LLMs with Reinforcement Learning on Natural Instructions",
    titleZh: "SUPERNOVA：用自然指令强化学习激发LLM通用推理能力",
    authors: "Ashima Suvarna et al.",
    arxivId: "2604.08477",
    tags: ["Reasoning", "RLHF"],
    why: "Data curation framework for RLVR on natural instructions — generalizes RL-driven reasoning beyond math/code to open-ended everyday tasks.",
    whyZh: "基于自然指令的RLVR数据策划框架，将强化学习驱动的推理能力从数学/代码拓展至通用任务。",
    pick: true,
  },
  {
    date: "2026-04-11",
    title: "Dynin-Omni: Omnimodal Unified Large Diffusion Language Model",
    titleZh: "Dynin-Omni：统一全模态大型扩散语言模型",
    authors: "Dynin AI et al.",
    arxivId: "2604.00007",
    tags: ["Diffusion LM", "Multimodal"],
    why: "First masked-diffusion omnimodal model unifying text, image, speech, and video — achieves strong results across 19 multimodal benchmarks.",
    whyZh: "首个掩码扩散全模态基础模型，统一文本、图像、语音与视频，19项基准表现强劲。",
  },
  {
    date: "2026-04-11",
    title: "Fast-dVLM: Efficient Block-Diffusion VLM via Direct Conversion from Autoregressive VLM",
    titleZh: "Fast-dVLM：从自回归VLM直接转换的高效块扩散视觉语言模型",
    authors: "Fast-dVLM Team et al.",
    arxivId: "2604.06832",
    tags: ["Diffusion LM", "Efficient Inference", "Vision"],
    why: "Converts AR VLMs to block-diffusion with KV-cache-compatible parallel decoding — brings diffusion inference speedups to vision-language models.",
    whyZh: "将自回归VLM转换为块扩散模型，支持KV缓存并行解码，将扩散推理加速能力引入视觉语言模型。",
  },
  {
    date: "2026-04-11",
    title: "Learning from the Right Rollouts: Data Attribution for PPO-based LLM Post-Training",
    titleZh: "从正确轨迹中学习：基于PPO的LLM后训练数据归因",
    authors: "I-PPO Team et al.",
    arxivId: "2604.01597",
    tags: ["RLHF", "Fine-tuning"],
    why: "I-PPO uses gradient-based influence scores to filter RL rollouts — reduces unfaithful CoT reasoning and accelerates PPO post-training.",
    whyZh: "I-PPO通过梯度影响分数过滤RL轨迹，减少不忠实CoT推理，加速PPO后训练收敛。",
  },
  {
    date: "2026-04-10",
    title: "SHAPE: Stage-aware Hierarchical Advantage via Potential Estimation for LLM Reasoning",
    titleZh: "SHAPE：面向LLM推理的阶段感知层级优势估计",
    authors: "Zhengyang Ai et al.",
    arxivId: "2604.06636",
    tags: ["Reasoning", "RLHF"],
    why: "Formalizes reasoning as state-space trajectories with hierarchical credit assignment — +3% accuracy and 30% fewer tokens by distinguishing efficient breakthroughs from mere verbosity.",
    whyZh: "将推理形式化为状态空间轨迹并引入层级信用分配，准确率提升3%、token减少30%，有效区分有效突破与冗余推理。",
    pick: true,
  },
  {
    date: "2026-04-10",
    title: "DARE: Diffusion Large Language Models Alignment and Reinforcement Executor",
    titleZh: "DARE：扩散大语言模型对齐与强化执行框架",
    authors: "Jingyi Yang et al.",
    arxivId: "2604.04215",
    tags: ["Diffusion LM", "Alignment", "RLHF"],
    why: "First unified open framework for post-training diffusion LLMs — brings RLHF and alignment tooling to both masked and block diffusion models, accelerating reproducible research.",
    whyZh: "首个统一的扩散LLM后训练开源框架，为掩码和块扩散模型提供RLHF与对齐工具，推动可复现研究。",
    pick: true,
  },
  {
    date: "2026-04-10",
    title: "LightThinker++: From Reasoning Compression to Memory Management",
    titleZh: "LightThinker++：从推理压缩到内存管理",
    authors: "Yuqi Zhu et al.",
    arxivId: "2604.03679",
    tags: ["Reasoning", "Efficient Inference"],
    why: "Upgrades LightThinker with explicit adaptive memory primitives — 70% peak token reduction and 26% faster inference by scheduling purposeful memory actions in long reasoning chains.",
    whyZh: "通过显式自适应内存原语升级LightThinker，峰值token减少70%、推理加速26%，适用于长推理链。",
    pick: true,
  },
  {
    date: "2026-04-10",
    title: "Rethinking Token Prediction: Tree-Structured Diffusion Language Model",
    titleZh: "重新思考Token预测：树结构扩散语言模型",
    authors: "Zihao Wu et al.",
    arxivId: "2604.03537",
    tags: ["Diffusion LM", "Theory"],
    why: "Exploits vocabulary hierarchy in masked diffusion — models intermediate latent states as ancestor nodes in a pre-built tree, enabling more structured and efficient training.",
    whyZh: "在掩码扩散中利用词汇层次结构，将中间潜在状态建模为词汇树祖先节点，训练更结构化高效。",
  },
  {
    date: "2026-04-10",
    title: "Dependency-Guided Parallel Decoding in Discrete Diffusion Language Models",
    titleZh: "离散扩散语言模型中的依赖引导并行解码",
    authors: "Liran Ringel et al.",
    arxivId: "2604.02560",
    tags: ["Diffusion LM", "Efficient Inference"],
    why: "DEMASK predictor estimates pairwise token dependencies to guide safe parallel unmasking — fixes quality degradation from distributional mismatch in discrete diffusion decoding.",
    whyZh: "DEMASK预测token间依赖关系，安全选择可并行解码的位置，解决离散扩散中分布不匹配导致的质量下降。",
  },
  {
    date: "2026-04-10",
    title: "MSA: Memory Sparse Attention for Efficient End-to-End Memory Model Scaling to 100M Tokens",
    titleZh: "MSA：面向1亿Token高效端到端记忆模型的稀疏注意力",
    authors: "EverMind AI",
    arxivId: "2603.23516",
    tags: ["Efficient Inference", "Pre-training"],
    why: "Scalable sparse attention + document-wise RoPE achieves near-linear complexity at 100M tokens — only 9% quality degradation vs 16K baseline, beating SOTA RAG and memory agents.",
    whyZh: "通过可扩展稀疏注意力和文档级RoPE实现1亿token近线性复杂度，相比16K基线仅降级9%，超越SOTA RAG系统。",
  },
  {
    date: "2025-02-14",
    title: "Large Language Diffusion Models (LLaDA)",
    titleZh: "大语言扩散模型 (LLaDA)",
    authors: "Nie et al.",
    arxivId: "2502.09992",
    tags: ["Diffusion LM", "Pre-training"],
    why: "First diffusion LM at 8B scale that matches LLaMA3 — proves AR is not the only path to powerful LLMs.",
    whyZh: "首个 8B 规模扩散语言模型，可与 LLaMA3 媲美 — 证明 AR 不是强大 LLM 的唯一路径。",
    pick: true,
    slug: "llada",
  },
  {
    date: "2025-02-28",
    title: "Block Diffusion: Interpolating Between Autoregressive and Diffusion Language Models",
    titleZh: "Block Diffusion: 在自回归与扩散语言模型之间插值",
    authors: "Arriola et al.",
    arxivId: "2503.09573",
    tags: ["Diffusion LM", "Efficient Inference"],
    why: "Elegant bridge between AR and diffusion — block size B lets you tune the speed/quality tradeoff continuously.",
    whyZh: "AR 和扩散之间的优雅桥梁 — 块大小 B 让你连续调节速度/质量权衡。",
    pick: true,
    slug: "block-diffusion",
  },
  {
    date: "2025-05-28",
    title: "Fast-dLLM: Training-free Acceleration of Diffusion LLM",
    authors: "Wu et al.",
    arxivId: "2505.22618",
    tags: ["Diffusion LM", "Efficient Inference"],
    why: "Practical 3-10x speedup for masked diffusion LMs with no retraining — makes diffusion LMs viable for production.",
    whyZh: "无需重新训练即可实现 3-10 倍加速 — 让扩散语言模型可用于生产环境。",
    pick: true,
    slug: "fast-dllm",
  },
  {
    date: "2024-06-11",
    title: "Simple and Effective Masked Diffusion Language Models (MDLM)",
    authors: "Sahoo et al.",
    arxivId: "2406.07524",
    tags: ["Diffusion LM", "Theory"],
    why: "Clean theoretical foundation for masked diffusion — derives the training loss from first principles, no hand-tuning.",
    whyZh: "掩码扩散的简洁理论基础 — 从基本原理推导训练损失，无需手动调整。",
    slug: "mdlm",
  },
  {
    date: "2023-05-29",
    title: "Direct Preference Optimization (DPO)",
    authors: "Rafailov et al.",
    arxivId: "2305.18290",
    tags: ["Alignment", "RLHF"],
    why: "Killed the reward model — rewrites RLHF as a simple binary loss. Became the default fine-tuning method for open-source LLMs.",
    whyZh: "消灭了奖励模型 — 将 RLHF 改写为简单的二元损失。成为开源 LLM 的默认微调方法。",
    pick: true,
    slug: "dpo",
  },
  {
    date: "2024-02-05",
    title: "DeepSeekMath: Pushing the Limits of Mathematical Reasoning (GRPO)",
    authors: "Shao et al.",
    arxivId: "2402.03300",
    tags: ["RL", "Math Reasoning"],
    why: "Introduces GRPO — removes the critic network from PPO by using group-relative rewards. Powers DeepSeek-R1.",
    whyZh: "引入 GRPO — 通过组相对奖励从 PPO 中移除 critic 网络。为 DeepSeek-R1 提供动力。",
    slug: "grpo",
  },
  {
    date: "2025-01-22",
    title: "DeepSeek-R1: Incentivizing Reasoning Capability in LLMs via RL",
    authors: "DeepSeek AI",
    arxivId: "2501.12948",
    tags: ["RL", "Reasoning", "Chain-of-Thought"],
    why: "Matches o1 on math/code using pure RL with GRPO — no supervised CoT data needed. Huge open-source release.",
    whyZh: "仅使用 GRPO 强化学习在数学/代码上匹配 o1 — 不需要监督 CoT 数据。重要的开源发布。",
    pick: true,
  },
  {
    date: "2017-06-12",
    title: "Attention Is All You Need",
    authors: "Vaswani et al.",
    arxivId: "1706.03762",
    tags: ["Transformer", "Architecture"],
    why: "The paper that started it all — replaced RNNs with attention. Everything in this repo builds on it.",
    whyZh: "一切的起点 — 用注意力替代 RNN。本站所有论文都建立在它之上。",
    slug: "attention-is-all-you-need",
  },
];

export const allTags = Array.from(
  new Set(dailyPapers.flatMap((p) => p.tags))
).sort();
