export interface DailyPaper {
  date: string; // ISO YYYY-MM-DD
  title: string;
  titleZh?: string;
  authors: string;
  arxivId: string;
  paperUrl?: string; // for non-arXiv papers (e.g. HuggingFace technical reports)
  tags: string[];
  /** One-line why it matters — English */
  why: string;
  /** One-line why it matters — Chinese */
  whyZh: string;
  /** Is this editor's pick */
  pick?: boolean;
  /** Has full deep-dive */
  slug?: string;
}

export const dailyPapers: DailyPaper[] = [
  {
    date: "2026-09-13",
    title: "NCP-ArchPreview Technical Report: Moving towards Latent Space Language Models through Next Concept Prediction",
    titleZh: "NCP-ArchPreview：通过下一概念预测迈向潜空间语言模型",
    authors: "The Intern-NCP Team",
    arxivId: "2609.10715",
    tags: ["Pre-training", "Theory"],
    why: "Jointly trains next-token and next-concept prediction: a product-quantized latent vocabulary represents multi-token concepts while preserving token-level autoregressive generation.",
    whyZh: "联合训练下一 token 与下一概念预测：在乘积量化潜空间中表示多 token 概念，同时保留 token 级自回归生成。",
    pick: true,
  },
  {
    date: "2026-09-13",
    title: "Unlocking Lossless Speedups in LLMs via Discrete Diffusion",
    titleZh: "通过离散扩散实现大语言模型无损加速",
    authors: "Subham Sekhar Sahoo et al.",
    arxivId: "2609.04010",
    tags: ["Diffusion LM", "Efficient Inference"],
    why: "The authors augment autoregressive LMs with lightweight diffusion weights and Ψ-Spec samplers for parallel decoding; they report up to 3× throughput over the base AR model.",
    whyZh: "作者为自回归语言模型加入轻量扩散权重与 Ψ-Spec 采样器，实现并行解码；论文报告相对基础自回归模型最高 3 倍吞吐提升。",
    pick: true,
  },
  {
    date: "2026-09-13",
    title: "Does Deeper Reasoning Compromise Alignment? Revealing and Mitigating Alignment Collapse in Large Reasoning Models",
    titleZh: "更深推理损害对齐吗？揭示并缓解大型推理模型中的对齐坍塌",
    authors: "Yu-Hang Wu et al.",
    arxivId: "2609.08186",
    tags: ["Alignment", "Reasoning"],
    why: "The paper reports that deeper reasoning can raise its proposed Alignment Loss Rate under perturbation, and introduces Reasoning Residual Alignment as a mitigation.",
    whyZh: "论文报告更深推理在扰动下可能提高其提出的对齐损失率（ALR），并提出 Reasoning Residual Alignment 作为缓解方法。",
    pick: true,
  },
  {
    date: "2026-09-13",
    title: "PELM: Power Efficient On-Device LLM Inference with Speculative Decoding and Dynamic Voltage Frequency Scaling",
    titleZh: "PELM：结合推测解码与动态电压频率调节的端侧LLM节能推理",
    authors: "Weisi Yang and Stephen Xia",
    arxivId: "2609.09662",
    tags: ["Efficient Inference"],
    why: "Combines speculative decoding, variable verification depth, and DVFS for on-device inference; the authors report up to 23.1% speedup and 52.4% lower energy use at comparable task performance.",
    whyZh: "结合推测解码、可变验证深度与动态电压频率调节用于端侧推理；作者报告在相近任务表现下最高 23.1% 加速和 52.4% 能耗降低。",
  },
  {
    date: "2026-09-13",
    title: "SpatialBlock: Enhancing Spatial Intelligence in LVLMs via Synthetic Block-Stacking Problem",
    titleZh: "SpatialBlock：通过合成积木堆叠任务增强视觉语言模型的空间智能",
    authors: "Soohyun Ryu et al.",
    arxivId: "2609.07064",
    tags: ["Multimodal", "Vision"],
    why: "SpatialBlock-15k supplies 15,000 synthetic block-stacking problems for 3D-to-2D projection, viewpoint transformation, and structural-composition reasoning; the authors report gains on real-world spatial tasks.",
    whyZh: "SpatialBlock-15k 提供 15,000 个合成积木堆叠问题，涵盖三维到二维投影、视角变换与结构组合推理；作者报告其在真实空间任务上有提升。",
  },
  {
    date: "2026-09-06",
    title: "Semantic-Space Exploration and Exploitation in RLVR for LLM Reasoning",
    titleZh: "RLVR强化学习中LLM推理的语义空间探索与利用",
    authors: "Fanding Huang et al.",
    arxivId: "2509.23808",
    tags: ["Reasoning", "RLHF"],
    why: "Studies how RLVR shapes semantic exploration in LLM reasoning — proposes strategies to improve coverage of valid reasoning paths.",
    whyZh: "研究RLVR如何塑造LLM推理的语义探索行为，提出提升有效推理路径覆盖率的策略。",
    pick: true,
  },
  {
    date: "2026-09-06",
    title: "Efficient Pre-Training with Token Superposition",
    titleZh: "基于Token叠加的高效预训练",
    authors: "Bowen Peng, Théo Gigant, and Jeffrey Quesnelle",
    arxivId: "2605.06546",
    tags: ["Pre-training", "Efficient Inference"],
    why: "Token-Superposition Training combines superposition and recovery phases; the authors report up to 2.5× lower total pretraining time at equal loss for a 10B A1B model.",
    whyZh: "Token-Superposition Training 结合叠加与恢复阶段；作者报告在 10B A1B 模型、相同损失条件下，总预训练时间最多缩短 2.5 倍。",
    pick: true,
  },
  {
    date: "2026-09-06",
    title: "Integrated and Cross-Architecture Interpretation of LLM Reasoning",
    titleZh: "LLM推理的跨架构统一解释框架",
    authors: "Leonardo Matthew Yauw, Wei-Bin Kou, and Yujiu Yang",
    arxivId: "2605.28006",
    tags: ["Theory", "Reasoning"],
    why: "Unified interpretability framework across LLM architectures traces and compares internal reasoning representations — enables systematic mechanistic understanding.",
    whyZh: "提出跨架构统一可解释性框架，追踪比较LLM内部推理表征，推动机制性理解系统化。",
  },
  {
    date: "2026-09-06",
    title: "Encoder-Decoder Diffusion Language Models for Efficient Training and Inference",
    titleZh: "高效训练与推理的编码器-解码器扩散语言模型",
    authors: "Marianne Arriola et al.",
    arxivId: "2510.22852",
    tags: ["Diffusion LM", "Efficient Inference"],
    why: "E2D2 is an encoder-decoder diffusion language model framework; the authors report improvements in training and inference efficiency.",
    whyZh: "E2D2 是编码器-解码器扩散语言模型框架；作者报告了训练与推理效率的提升。",
  },
  {
    date: "2026-08-30",
    title: "LLaDA MoE v2: Scaling Mixture-of-Experts Diffusion Language Models",
    titleZh: "LLaDA MoE v2：扩散语言模型的MoE规模化研究",
    authors: "Fengqi Zhu et al.",
    arxivId: "2608.03457",
    tags: ["Diffusion LM", "MoE", "Pre-training"],
    why: "First systematic MoE scaling study for diffusion LMs — 30B-A3B on 23.5T tokens, revealing that AR scaling laws don't transfer directly to diffusion models.",
    whyZh: "首个MoE扩散LM系统性缩放研究，30B-A3B在23.5T token上训练，揭示AR缩放规律不直接适用于扩散语言模型。",
    pick: true,
  },
  {
    date: "2026-08-30",
    title: "SelFusion: Self-distillation for Diffusion Language Models",
    titleZh: "SelFusion：扩散语言模型的自蒸馏框架",
    authors: "Hyeongsoo Lim et al.",
    arxivId: "2608.22898",
    tags: ["Diffusion LM", "Fine-tuning"],
    why: "ACL 2026: bidirectional self-distillation between hard/easy masking schedules fixes KD failure modes in diffusion LMs — trained students routinely outperform LLM teachers.",
    whyZh: "ACL 2026：强弱掩码间双向自蒸馏，解决扩散LM知识蒸馏失效问题，学生模型常超越LLM教师。",
    pick: true,
  },
  {
    date: "2026-08-30",
    title: "MUX: Continuous Reasoning via Multiplexed Tokens",
    titleZh: "MUX：通过复用Token实现连续推理",
    authors: "Ayhan Suleymanzade et al.",
    arxivId: "2607.18264",
    tags: ["Reasoning", "Efficient Inference"],
    why: "Each MUX latent token is a weighted superposition of multiple reasoning steps — enables parallel exploration without beam-search overhead, beating latent baselines across 32 settings on 4 models.",
    whyZh: "MUX潜在token通过加权叠加压缩多推理步骤，无需束搜索即可并行探索，在4个模型的32项评估中超越潜在推理基线。",
    pick: true,
  },
  {
    date: "2026-08-30",
    title: "xPress: Parallel Refinement for Diffusion Drafters in Speculative Decoding",
    titleZh: "xPress：推测解码中扩散草稿器的并行精炼",
    authors: "Anonymous et al.",
    arxivId: "2608.02438",
    tags: ["Diffusion LM", "Efficient Inference"],
    why: "Lightweight causal refiner restores joint distribution from per-position marginals in block-diffusion drafters — improves acceptance rate with one parallel pass, no extra model needed.",
    whyZh: "轻量因果精炼器将块扩散草稿器的边际分布还原为联合分布，单次并行传播提升推测解码接受率。",
  },
  {
    date: "2026-08-30",
    title: "Dependency-Aware Revocable Decoding for Efficient Diffusion LLM Inference",
    titleZh: "依赖感知可撤销解码：高效扩散LLM推理",
    authors: "Anonymous et al.",
    arxivId: "2608.26574",
    tags: ["Diffusion LM", "Efficient Inference"],
    why: "Models token dependency structure to selectively revoke committed positions during decoding — reduces quality loss from premature commits in masked diffusion LMs.",
    whyZh: "建模token依赖结构，允许选择性撤销已提交位置，减少掩码扩散LM提前提交导致的质量损失。",
  },
  {
    date: "2026-08-23",
    title: "Agentic ESOpt: Fine-Tuning Long-Horizon LLM Agents with Minimal GPU Requirements",
    titleZh: "Agentic ESOpt：以最低显存需求微调长程LLM智能体",
    authors: "Zhi Zheng et al.",
    arxivId: "2608.17310",
    tags: ["Agent", "Fine-tuning"],
    why: "Evolution strategies fine-tune long-horizon LLM agents using only inference-level GPU memory — no backpropagation, scales to frontier models.",
    whyZh: "进化策略仅需推理级显存微调长程LLM智能体，无需反向传播，可扩展至前沿大模型，本周HuggingFace热榜。",
    pick: true,
  },
  {
    date: "2026-08-23",
    title: "Fewer Tokens, Smaller Cache: Reward-Coordinated Efficient Reasoning",
    titleZh: "更少Token，更小缓存：奖励协调的高效推理",
    authors: "Qiyuan Zhu et al.",
    arxivId: "2608.04771",
    tags: ["Reasoning", "Efficient Inference"],
    why: "ReCo uses process reward to jointly compress KV-cache and control generation length — cuts overthinking in Large Reasoning Models without accuracy loss.",
    whyZh: "ReCo以过程奖励同步压缩KV缓存与控制生成长度，大幅削减大推理模型过度思考，精度无损。",
    pick: true,
  },
  {
    date: "2026-08-23",
    title: "AcceptMoE: Commitment-Weighted Self-Sizing Verifier Expert Sets for Efficient MoE Speculative Decoding",
    titleZh: "AcceptMoE：承诺加权自适应验证专家集用于高效MoE推测解码",
    authors: "Shuang Liang et al.",
    arxivId: "2608.02989",
    tags: ["MoE", "Efficient Inference"],
    why: "Commitment-weighted expert selector self-sizes verifier sets in MoE speculative decoding — eliminates manual expert budget and cuts wasted activations.",
    whyZh: "承诺加权专家选择器自动调整MoE推测解码验证集规模，无需手动设定专家预算，减少冗余激活。",
  },
  {
    date: "2026-08-23",
    title: "AI4AI-Bench: Benchmarking LLM Agents in Algorithmic Design for Recursive Self-Improvement",
    titleZh: "AI4AI-Bench：评估LLM智能体递归自改进算法设计能力的基准",
    authors: "Yizhe Chi et al.",
    arxivId: "2608.20318",
    tags: ["Agent", "Benchmark"],
    why: "Gives LLM agents 4 hours to rewrite training algorithms across 10 real research repos — first direct evaluation of recursive self-improvement capability.",
    whyZh: "让LLM智能体在4小时内重写10个研究代码库训练算法，首个直接量化递归自改进能力的基准。",
  },
  {
    date: "2026-08-16",
    title: "Training AI Scientists to Replicate Research",
    titleZh: "训练AI科学家复现研究成果",
    authors: "Damon Falck et al.",
    arxivId: "2608.13331",
    tags: ["Agent", "Benchmark"],
    why: "Replica task space + 27B Faraday agent surpasses Claude Opus 4.8 and GPT-5.5 on paper replication — first scalable benchmark for AI scientific replication with rubric-based auto-judging.",
    whyZh: "27B Faraday智能体在论文复现上超越GPT-5.5，Replica首创AI科学复现基准与自动评判体系。",
    pick: true,
  },
  {
    date: "2026-08-16",
    title: "BDH-CQ: In-Context Learning with Recurrent Latent Reasoning",
    titleZh: "BDH-CQ：循环隐空间推理增强的上下文学习",
    authors: "Pathway Research",
    arxivId: "2608.09888",
    tags: ["Reasoning", "Efficient Inference"],
    why: "150M model reasons entirely in latent space — no verbalized CoT, 29.5% pass@2 on ARC-AGI at $0.0007/task — 11x cheaper than GPT-5.6 on abstract reasoning.",
    whyZh: "1.5亿参数模型完全在隐空间推理，无需语言化思维链，ARC-AGI推理每次仅$0.0007，效率极高。",
    pick: true,
  },
  {
    date: "2026-08-16",
    title: "AI4AI at Test-Time: Strong-to-Weak Capability Transfer via Harnesses",
    titleZh: "AI4AI推理时框架：强模型向弱模型的能力迁移",
    authors: "AI4AI Team",
    arxivId: "2608.12307",
    tags: ["Reasoning", "Efficient Inference"],
    why: "Builder model constructs inference-time harnesses that boost weaker models without retraining — gains from offloading reasoning to deterministic code, not more sampling.",
    whyZh: "强模型构建推理框架让弱模型无需重训即受益——核心收益来自将推理转为确定性代码，而非更多采样。",
  },
  {
    date: "2026-08-16",
    title: "OpenART: Scaling Agent Red Teaming via Open-Ended Environment Evolution",
    titleZh: "OpenART：通过开放式环境演化扩展智能体红队测试",
    authors: "AI45Lab et al.",
    arxivId: "2608.00677",
    tags: ["Agent", "Benchmark"],
    why: "10,000+ stateful scenarios across 50 domains; EMHA adversarial evolution — first scalable safety benchmark for long-horizon agent behavior under persistent state.",
    whyZh: "1万余有状态场景+EMHA对抗演化，首个系统评估持久状态下长程智能体安全的大规模基准。",
  },
  {
    date: "2026-08-16",
    title: "LoRA-Diffusion: Parameter-Efficient Fine-Tuning via Low-Rank Trajectory Decomposition",
    titleZh: "LoRA-Diffusion：基于低秩轨迹分解的参数高效微调",
    authors: "Iman Khazrak et al.",
    arxivId: "2608.12328",
    tags: ["LoRA", "Fine-tuning", "Diffusion LM"],
    why: "Low-rank adapters on the denoising trajectory — not model weights — bring PEFT to diffusion LMs with composable multi-task merging at inference without retraining.",
    whyZh: "对去噪轨迹做低秩分解，将PEFT引入扩散LM，支持推理时多任务模块无缝合并，无需重训练。",
  },
  {
    date: "2026-08-16",
    title: "LLMs Are Not Good Strategists, Yet Memory-Enhanced Agency Boosts Reasoning",
    titleZh: "LLM策略推理欠佳但记忆增强可提升长程推理",
    authors: "Yi Wu and Zhimin Hu",
    arxivId: "2608.12626",
    tags: ["Agent", "Reasoning"],
    why: "EpicStar: episodic memory bank + working memory overcomes strategic drift in long-horizon tasks — memory architecture matters more than reasoning depth alone.",
    whyZh: "EpicStar通过情景记忆+工作记忆克服长程智能体策略漂移，记忆架构比推理深度更为关键。",
  },
  {
    date: "2026-08-09",
    title: "ParVL: Parallel Scaling and Expandable Compute Allocation for Multimodal LLMs",
    titleZh: "ParVL：多模态LLM的并行扩展与可扩展计算分配",
    authors: "Yang Yang et al.",
    arxivId: "2608.04010",
    tags: ["Multimodal", "Efficient Inference"],
    why: "Reuses ViT + LLM backbone params across parallel vision-language branches to scale compute without memory overhead — first systematic study of vision-language compute allocation trade-offs.",
    whyZh: "通过在并行视觉语言分支间复用ViT和LLM骨干参数扩展计算而无内存开销，首次系统研究多模态LLM视觉语言计算分配权衡。",
    pick: true,
  },
  {
    date: "2026-08-09",
    title: "Provable Benefits of RLVR over SFT for Reasoning Models: Learning to Backtrack Efficiently",
    titleZh: "RLVR相对SFT的可证明优势：高效学习回溯",
    authors: "Stanley Wei and Juno Kim",
    arxivId: "2606.22938",
    tags: ["Reasoning", "Theory"],
    why: "Formal proof via graph pathfinding that RLVR learns efficient backtracking from dead ends while SFT on golden paths cannot — exponential inference-compute separation.",
    whyZh: "通过图路径搜索形式化证明RLVR能从死胡同高效回溯而SFT无法做到，两者推理时计算效率差距达指数级。",
    pick: true,
  },
  {
    date: "2026-08-09",
    title: "Flow Reasoning Models: Scaling Reasoning Through Iterative Self-Refinement",
    titleZh: "流推理模型：通过迭代自精化扩展推理能力",
    authors: "Alec Helbling et al.",
    arxivId: "2606.29150",
    tags: ["Diffusion LM", "Reasoning"],
    why: "Discrete flow models act as self-verifying solvers via self-conditioning and DPO-based failure avoidance — reaches 99.2% Sudoku solve rate in 7 forward passes, 8× fewer than masked diffusion.",
    whyZh: "离散流模型通过自条件化与DPO失败规避作为自验证求解器，仅7次前向传播解决99.2%数独，效率是掩码扩散的8倍。",
  },
  {
    date: "2026-08-09",
    title: "MODE: Modality-Decomposed Expert-Level Mixed-Precision Quantization for MoE Multimodal LLMs",
    titleZh: "MODE：MoE多模态LLM的模态分解专家级混合精度量化",
    authors: "Yuanteng Chen et al.",
    arxivId: "2606.17118",
    tags: ["MoE", "Quantization", "Multimodal"],
    why: "Decomposes expert-selection frequency by modality and adds per-modality sensitivity signals to fix quantization bias in MoE vision-language models — outperforms uniform expert-level schemes.",
    whyZh: "通过模态分解专家选择频率并加入逐模态量化敏感度信号，修正MoE视觉语言模型中的量化偏差，优于均匀专家级方案。",
  },
  {
    date: "2026-08-09",
    title: "Efficient Sequential Evaluation of Large Language Models",
    titleZh: "大语言模型的高效序列化评估",
    authors: "Chia-Yu Hsu and Shubhanshu Shekhar",
    arxivId: "2607.17409",
    tags: ["Benchmark", "Efficient Inference"],
    why: "Sequential hypothesis testing framework for LLM benchmarking — actively queries informative test cases to shrink confidence intervals faster using historical LLM performance data.",
    whyZh: "将序列假设检验引入LLM基准测试，通过历史性能数据主动选择信息量最大的测试案例，大幅提升置信区间收敛速度。",
  },
  {
    date: "2026-07-26",
    title: "Distilled Reinforcement Learning for LLM Post-training",
    titleZh: "蒸馏强化学习用于LLM后训练",
    authors: "Chen Wang et al.",
    arxivId: "2607.17247",
    tags: ["RLHF", "Fine-tuning", "Reasoning"],
    why: "Uses the teacher model to redistribute policy-gradient signal at the token level — fine-grained credit assignment that beats pure RL or on-policy distillation alone.",
    whyZh: "用教师模型在token级别重新分配策略梯度信号，实现细粒度信用分配，效果超越纯RL与在线蒸馏各自单独使用。",
    pick: true,
  },
  {
    date: "2026-07-26",
    title: "SLIM-RL: Risk-Budgeted Random-Masking RL for Diffusion LLMs Without Trajectory Slicing",
    titleZh: "SLIM-RL：免轨迹切分的扩散LLM风险预算随机掩码强化学习",
    authors: "Ruikang Zhao et al.",
    arxivId: "2607.00208",
    tags: ["Diffusion LM", "RLHF"],
    why: "τ-budget decoder bounds commit risk per rollout step, enabling RL for diffusion LLMs without costly trajectory slicing — matches TraceRL MATH500 accuracy on 0.46× training samples.",
    whyZh: "τ预算解码器逐步约束提交风险，免去高开销轨迹切分，在0.46倍训练样本下匹配TraceRL的MATH500表现，数学和代码均有提升。",
    pick: true,
  },
  {
    date: "2026-07-26",
    title: "KronQ: LLM Quantization via Kronecker-Factored Hessian",
    titleZh: "KronQ：基于Kronecker因子化Hessian的LLM量化",
    authors: "Donghyun Lee et al.",
    arxivId: "2607.07964",
    tags: ["Quantization", "Efficient Inference"],
    why: "Kronecker-factored Hessian encodes gradient covariance into the quantization objective — 7.93 perplexity at 2-bit on LLaMA-3-70B where GPTQ diverges entirely. COLM 2026.",
    whyZh: "Kronecker因子化Hessian将梯度协方差融入量化目标，在LLaMA-3-70B的2-bit量化中困惑度7.93，而GPTQ在此精度完全发散，COLM 2026录用。",
  },
  {
    date: "2026-07-26",
    title: "Token Budget Saturation and Mechanistic Early Detection of Reasoning Non-Convergence in Chain-of-Thought Models",
    titleZh: "CoT模型中Token预算饱和与推理非收敛的机械式早期检测",
    authors: "Renuka Oladri et al.",
    arxivId: "2607.21433",
    tags: ["Reasoning", "Theory"],
    why: "Mechanistically identifies when CoT token budgets saturate without reaching a valid answer — enables early detection of non-converging reasoning, saving inference compute.",
    whyZh: "机械性分析CoT Token预算耗尽却无法得出有效答案的饱和现象，实现推理非收敛的早期检测，节省推理计算资源。",
  },
  {
    date: "2026-07-26",
    title: "SLAI T-Rex: Full-Parameter Post-training of the DeepSeek-V4 Family on Ascend SuperPOD",
    titleZh: "SLAI T-Rex：在昇腾SuperPOD上对DeepSeek-V4系列进行全参数后训练",
    authors: "SLAI Team et al.",
    arxivId: "2607.20145",
    tags: ["Fine-tuning", "MoE"],
    why: "End-to-end hierarchical optimization for trillion-scale MoE on Ascend NPUs — 34.22% MFU at 2.93× baseline throughput; specialized SFT model outperforms GPT-5.4-Mini on OR tasks.",
    whyZh: "面向昇腾NPU超节点的万亿参数MoE全参数后训练框架，MFU达34.22%，吞吐是基线的2.93倍，专用SFT模型在运筹优化任务上超越GPT-5.4-Mini。",
  },
  {
    date: "2026-07-19",
    title: "SEED: Self-Evolving On-Policy Distillation for Agentic Reinforcement Learning",
    titleZh: "SEED：面向智能体强化学习的自进化在线策略蒸馏",
    authors: "Jinyang Wu et al.",
    arxivId: "2607.14777",
    tags: ["Agent", "RLHF"],
    why: "Extracts reusable hindsight skills from completed RL trajectories and distills them as dense token-level on-policy supervision — strong gains on long-horizon agentic tasks.",
    whyZh: "从已完成RL轨迹提取可复用后见技能，蒸馏为密集token级在线监督信号，在长程智能体任务上显著提升性能。",
    pick: true,
  },
  {
    date: "2026-07-19",
    title: "Sangam: Efficiently Serving Diffusion LLMs with the AR Stack",
    titleZh: "Sangam：用自回归技术栈高效服务扩散大语言模型",
    authors: "Sangam Team et al.",
    arxivId: "2607.04206",
    tags: ["Diffusion LM", "Efficient Inference"],
    why: "First production serving system for cached dLLM inference — deficit token-budget scheduler cuts mean latency 9–20% on decode-heavy workloads via hybrid prefill/decode routing.",
    whyZh: "首个扩散LLM生产服务系统，赤字token预算调度器通过混合路由在解码密集负载上降低延迟9-20%。",
    pick: true,
  },
  {
    date: "2026-07-19",
    title: "VideoChat3: Fully Open Video MLLM for Efficient and Generalist Video Understanding",
    titleZh: "VideoChat3：全开放高效通用视频多模态大语言模型",
    authors: "VideoChat3 Team et al.",
    arxivId: "2607.14935",
    tags: ["Multimodal", "Vision"],
    why: "Fully open video MLLM for diverse durations and interaction modes — #1 trending on HuggingFace this week with strong cross-benchmark video understanding results.",
    whyZh: "全开放视频多模态LLM，覆盖多时长视频与多交互模式，本周HuggingFace热度第一，跨基准视频理解能力强。",
  },
  {
    date: "2026-07-19",
    title: "TACG: Trajectory-Aware Commit Gating for Diffusion Language Model Decoding",
    titleZh: "TACG：扩散语言模型解码的轨迹感知提交门控",
    authors: "Chengcheng Wang et al.",
    arxivId: "2607.03236",
    tags: ["Diffusion LM", "Efficient Inference"],
    why: "Training-free dLLM decoder combining temporal logit guidance with history gating — reduces denoising steps while preserving accuracy on code/math benchmarks.",
    whyZh: "扩散LLM免训练解码器，时序logit引导+历史门控减少去噪步骤，代码/数学精度不降。",
  },
  {
    date: "2026-07-12",
    title: "Nemotron-Labs-Diffusion: A Tri-Mode Language Model Unifying Autoregressive, Diffusion, and Self-Speculation Decoding",
    titleZh: "Nemotron-Labs-Diffusion：统一自回归、扩散与自推测解码的三模态语言模型",
    authors: "NVIDIA et al.",
    arxivId: "2607.05722",
    tags: ["Diffusion LM", "Efficient Inference", "Pre-training"],
    why: "NVIDIA's 3B/8B/14B open model trains AR and diffusion jointly — at inference, diffusion drafts and AR verifies, yielding 6× tokens per forward pass vs Qwen3-8B.",
    whyZh: "英伟达开源3B/8B/14B三模态模型，联合训练AR与扩散目标，推理时扩散起草、AR验证，每次前向传播生成token数是Qwen3-8B的6倍。",
    pick: true,
  },
  {
    date: "2026-07-12",
    title: "Set Diffusion: Interpolating Token Orderings Between Autoregression and Diffusion for Fast and Flexible Decoding",
    titleZh: "集合扩散：在自回归与扩散之间插值实现快速灵活解码",
    authors: "Marianne Arriola and Volodymyr Kuleshov",
    arxivId: "2607.01775",
    tags: ["Diffusion LM", "Efficient Inference", "Theory"],
    why: "ICML 2026: factorizes over flexible-position token sets with KV-cache support — fixes diffusion LMs' fixed-length and no-caching limitations in one architecture.",
    whyZh: "ICML 2026：对灵活位置token集合分解建模并支持KV缓存，同时解决扩散LM固定长度生成和无法缓存两大瓶颈。",
    pick: true,
  },
  {
    date: "2026-07-12",
    title: "Agon: Competitive Cross-Model RL with Implicit Rival Grading of Reasoning",
    titleZh: "Agon：基于隐式对手评分的竞争跨模型强化学习推理",
    authors: "Vladislav Beliaev",
    arxivId: "2607.07690",
    tags: ["Reasoning", "RLHF"],
    why: "Two models compete on the same problem and grade each other implicitly — no reward model, no process labels, with an ever-stronger rival as natural curriculum.",
    whyZh: "两个模型竞争同一问题并相互隐式打分，无需奖励模型和过程标注，对手持续变强形成自然课程。",
    pick: true,
  },
  {
    date: "2026-07-12",
    title: "Message Passing Enables Efficient Reasoning",
    titleZh: "消息传递驱动高效推理",
    authors: "Xuecheng Liu et al.",
    arxivId: "2607.01077",
    tags: ["Reasoning", "Efficient Inference"],
    why: "MPLMs replace fork-join parallelism with send/receive primitives — threads preempt each other on partial info, cutting redundant CoT computation at scale.",
    whyZh: "MPLMs用发送/接收原语替代分叉-合并并行，线程基于部分信息提前终止，大幅削减冗余思维链计算量。",
  },
  {
    date: "2026-07-12",
    title: "KARA: Efficient Reasoning LLM Serving via Sliding-Window KV Cache Compression",
    titleZh: "KARA：通过滑动窗口KV缓存压缩实现高效推理LLM服务",
    authors: "KARA Team et al.",
    arxivId: "2607.01237",
    tags: ["Efficient Inference", "Reasoning"],
    why: "Sliding-window KV eviction tailored for long reasoning chains — selectively preserves important KV pairs to reduce memory overhead and lift serving throughput.",
    whyZh: "针对长推理链的滑动窗口KV驱逐策略，选择性保留重要KV对，降低内存开销并提升推理服务吞吐量。",
  },
  {
    date: "2026-07-05",
    title: "TARPO: Token-Wise Latent-Explicit Reasoning via Action-Routing Policy Optimization",
    titleZh: "TARPO：基于动作路由策略优化的逐token潜在-显式推理",
    authors: "TARPO Team et al.",
    arxivId: "2606.05859",
    tags: ["Reasoning", "RLHF"],
    why: "Routes each token to latent or explicit reasoning chains via RL — outperforms GRPO on math and code benchmarks with lower KV cache pressure and sharper chain boundaries.",
    whyZh: "通过强化学习为每个token动态选择潜在或显式推理链，在数学和代码基准上超越GRPO，同时降低KV缓存压力。",
    pick: true,
  },
  {
    date: "2026-07-05",
    title: "Reasoning Quality Emerges Early: Data Curation for Reasoning Models",
    titleZh: "推理质量早期涌现：面向推理模型的数据策划",
    authors: "Authors et al.",
    arxivId: "2606.26797",
    tags: ["Reasoning", "Fine-tuning"],
    why: "Reasoning quality signals appear in early training steps — enables cheap data curation that cuts post-training compute while preserving or improving final benchmark accuracy.",
    whyZh: "推理质量信号在训练早期即可显现，支持以极少计算资源完成推理模型的数据策划，大幅降低后训练成本。",
    pick: true,
  },
  {
    date: "2026-07-05",
    title: "Nemotron-Labs-TwoTower: Diffusion Language Modeling with Pretrained Autoregressive Context",
    titleZh: "Nemotron-Labs双塔：结合预训练自回归上下文的扩散语言建模",
    authors: "NVIDIA Nemotron Labs et al.",
    arxivId: "2606.26493",
    tags: ["Diffusion LM", "Pre-training"],
    why: "Two-tower architecture separates context encoding from denoising — reuses pretrained AR representations to lift diffusion LM quality without full from-scratch training.",
    whyZh: "双塔架构将上下文编码与去噪分离，复用预训练自回归表示提升扩散LM质量，避免从头训练的高成本。",
  },
  {
    date: "2026-07-05",
    title: "Data-Efficient Autoregressive-to-Diffusion Language Models via On-Policy Distillation",
    titleZh: "基于策略蒸馏的数据高效自回归到扩散语言模型转换（OPDLM）",
    authors: "OPDLM Team et al.",
    arxivId: "2606.06712",
    tags: ["Diffusion LM", "Fine-tuning"],
    why: "On-policy distillation converts any pretrained AR LM to a diffusion LM with far less data than training from scratch — practical low-cost path to diffusion adoption.",
    whyZh: "基于策略蒸馏将预训练自回归LM高效转换为扩散LM，所需数据远少于从头训练，为扩散模型实际部署提供低成本新路径。",
  },
  {
    date: "2026-07-05",
    title: "Revise, Don't Freeze: Sampler-Matched Training for Self-Correcting Masked Diffusion Language Models",
    titleZh: "修正而非冻结：掩码扩散语言模型的采样匹配自校正训练",
    authors: "Authors et al.",
    arxivId: "2606.01026",
    tags: ["Diffusion LM", "Fine-tuning"],
    why: "Sampler-matched training aligns the training objective with the inference process — enables self-correction in masked diffusion LMs with no added inference cost.",
    whyZh: "采样匹配训练将目标函数与推理过程对齐，使掩码扩散LM具备自我修正能力，无额外推理开销。",
  },
  {
    date: "2026-07-05",
    title: "Reliable Chain-of-Thought via Prefix Consistency",
    titleZh: "基于前缀一致性的可靠思维链",
    authors: "Authors et al.",
    arxivId: "2605.07654",
    tags: ["Reasoning", "Theory"],
    why: "Prefix consistency score detects when a reasoning chain is about to derail — test-time filtering improves CoT accuracy with no retraining across multiple models and domains.",
    whyZh: "前缀一致性分数预测推理链偏离风险，测试时过滤无需重训练即可在多个模型和领域上提升CoT准确率。",
  },
  {
    date: "2026-06-28",
    title: "Improved Large Language Diffusion Models",
    titleZh: "改进的大型语言扩散模型（iLLaDA）",
    authors: "Shen Nie et al.",
    arxivId: "2606.25331",
    tags: ["Diffusion LM", "Pre-training"],
    why: "iLLaDA scales masked diffusion pre-training to 12T tokens with fully bidirectional attention — +21.6pt BBH and +14.5pt MATH over LLaDA, setting a new bar for diffusion LMs.",
    whyZh: "iLLaDA将掩码扩散预训练扩展至12T token，完全双向注意力——BBH超越LLaDA 21.6分、MATH提升14.5分，树立扩散语言模型新标杆。",
    pick: true,
  },
  {
    date: "2026-06-28",
    title: "Beyond Entropy: Learning from Token-Level Distributional Deviations for LLM Reasoning",
    titleZh: "超越熵：从Token级分布偏差学习以提升LLM推理",
    authors: "Xuanzhi Feng et al.",
    arxivId: "2606.19771",
    tags: ["Reasoning", "RLHF"],
    why: "ICT identifies critical token branching points via Jensen-Shannon divergence — simultaneously fixes entropy collapse and explosion in RLVR, stabilizing reasoning training.",
    whyZh: "ICT通过logit分布间JS散度识别关键token分支点，同时解决RLVR训练中的熵坍塌与熵爆炸问题，显著提升推理训练稳定性。",
    pick: true,
  },
  {
    date: "2026-06-28",
    title: "ReSum: Synergizing LLM Reasoning and Summarization with Reinforcement Learning",
    titleZh: "ReSum：利用强化学习协同LLM推理与摘要生成",
    authors: "Xucong Wang et al.",
    arxivId: "2606.13316",
    tags: ["Reasoning", "RLHF"],
    why: "RLVR framework trains LLMs to self-summarize reasoning trajectories — prevents coherence degradation and context exhaustion from overly long rollouts in long-horizon tasks.",
    whyZh: "通过RLVR训练LLM主动将推理轨迹压缩为摘要，解决长程推理中的连贯性下降与上下文耗尽问题。",
  },
  {
    date: "2026-06-28",
    title: "PerceptionDLM: Parallel Region Perception with Multimodal Diffusion Language Models",
    titleZh: "PerceptionDLM：基于多模态扩散语言模型的并行区域感知",
    authors: "PerceptionDLM Team et al.",
    arxivId: "2606.19534",
    tags: ["Diffusion LM", "Multimodal"],
    why: "Multimodal diffusion LM for efficient parallel region-level image perception — SOTA among open-source diffusion MLLMs with a new 2345-question multi-region benchmark.",
    whyZh: "基于扩散LLM的多模态模型，实现图像多区域并行感知，配备2345条手工验证基准问答，开源扩散MLLM中达SOTA。",
  },
  {
    date: "2026-06-21",
    title: "Does Reasoning Preserve Alignment? On the Trustworthiness of Large Reasoning Models",
    titleZh: "推理能力保留对齐性吗？大型推理模型可信度评估",
    authors: "et al.",
    arxivId: "2606.11046",
    tags: ["Reasoning", "Alignment", "Benchmark"],
    why: "Benchmarks six trustworthiness dimensions on reasoning models — finds alignment regressions including increased toxicity, amplified stereotyping, and miscalibrated refusal despite reasoning gains.",
    whyZh: "在安全性、毒性等6个维度评测推理模型，发现推理提升伴随对齐退化：毒性增加、刻板印象放大、拒绝校准失准。",
    pick: true,
  },
  {
    date: "2026-06-21",
    title: "ExpRL: Exploratory RL for LLM Mid-Training",
    titleZh: "ExpRL：大语言模型中间训练的探索性强化学习",
    authors: "et al.",
    arxivId: "2606.17024",
    tags: ["RLHF", "Reasoning", "Pre-training"],
    why: "RL mid-training on large human QA corpora expands base model solution coverage — unlocks RLVR on checkpoints that previously failed due to sparse reward from low coverage.",
    whyZh: "在大规模人类QA语料上进行RL中间训练以扩大解方案覆盖率，解锁此前因低覆盖率导致稀疏奖励失效的检查点。",
    pick: true,
  },
  {
    date: "2026-06-21",
    title: "Rethinking Shrinkage Bias in LLM FP4 Pretraining: Geometric Origin, Systemic Impact, and UFP4 Recipe",
    titleZh: "重思LLM FP4预训练中的收缩偏差：几何根源、系统性影响与UFP4方案",
    authors: "et al.",
    arxivId: "2606.20381",
    tags: ["Pre-training", "Quantization"],
    why: "Identifies shrinkage bias as the geometric root of FP4 pretraining instability; UFP4 recipe resolves it — enabling memory-efficient FP4 pretraining at LLM scale.",
    whyZh: "揭示收缩偏差为FP4预训练不稳定的几何根源，UFP4方案有效解决该问题，实现大规模高效FP4预训练。",
    pick: true,
  },
  {
    date: "2026-06-21",
    title: "Data Augmentations for Data-Constrained Language Model Pretraining",
    titleZh: "数据受限语言模型预训练的数据增强方法",
    authors: "et al.",
    arxivId: "2606.16246",
    tags: ["Pre-training"],
    why: "Data augmentation as regularization for multi-epoch pretraining on fixed corpora — enables effective training for hundreds of epochs in compute-abundant, data-constrained regimes.",
    whyZh: "将数据增强作为正则化手段用于固定语料多轮预训练，在算力充足、数据受限的新范式下支持数百轮有效训练。",
  },
  {
    date: "2026-06-21",
    title: "Predictable Scaling Laws of Optimal Hyperparameters for LLM Continued Pre-training",
    titleZh: "LLM持续预训练最优超参数的可预测缩放定律",
    authors: "et al.",
    arxivId: "2606.05610",
    tags: ["Pre-training"],
    why: "Derives predictable scaling laws for optimal learning rate and batch size in continued pretraining — replaces costly grid search with principled, transferable hyperparameter estimates.",
    whyZh: "推导持续预训练最优学习率和批量大小的缩放定律，以有原则的可迁移估计代替昂贵的网格搜索，降低训练成本。",
  },
  {
    date: "2026-06-21",
    title: "Fine-tuning Multi-modal LLMs with ART: Art-based Reinforcement Training",
    titleZh: "ART：基于艺术强化训练的多模态LLM微调方法",
    authors: "et al.",
    arxivId: "2606.11854",
    tags: ["Fine-tuning", "Multimodal", "RLHF"],
    why: "ART combines parameter-efficient fine-tuning with RL reward signals for multimodal LLMs — improves visual instruction following without full fine-tuning compute costs.",
    whyZh: "ART将参数高效微调与RL奖励信号结合用于多模态LLM，在不承担全量微调成本的前提下提升视觉指令遵循能力。",
  },
  {
    date: "2026-06-14",
    title: "Rethinking the Divergence Regularization in LLM RL",
    titleZh: "重新审视LLM强化学习中的散度正则化",
    authors: "Jiarui Yao et al.",
    arxivId: "2606.09821",
    tags: ["RLHF", "Reasoning"],
    why: "Replaces ratio-clipping in PPO/GRPO with a smooth quadratic divergence regularizer — more stable post-training across dense and MoE models at BF16 and FP8, no value model needed.",
    whyZh: "用平滑散度正则化替换PPO/GRPO中的比率裁剪，在密集与MoE架构的BF16/FP8精度下均更稳定，无需价值网络。",
    pick: true,
  },
  {
    date: "2026-06-14",
    title: "Organize then Retrieve: Hierarchical Memory Navigation for Efficient Agents",
    titleZh: "先组织后检索：高效智能体的层级记忆导航",
    authors: "Hao-Lun Hsu et al.",
    arxivId: "2606.11680",
    tags: ["Agent", "Efficient Inference"],
    why: "HORMA structures agent memory as a file-system hierarchy — navigation-based retrieval gives long-horizon agents temporally consistent access without lossy compression.",
    whyZh: "HORMA将智能体记忆组织为文件系统层级，通过主动导航检索支持长时域任务，避免有损压缩导致的信息丢失。",
    pick: true,
  },
  {
    date: "2026-06-14",
    title: "Operadic Consistency: A Label-Free Signal for Compositional Reasoning Failures in LLMs",
    titleZh: "算符一致性：LLM组合推理失败的无标签诊断信号",
    authors: "Nathaniel Bottman et al.",
    arxivId: "2606.13649",
    tags: ["Reasoning", "Theory"],
    why: "Uses operad theory to check whether an LLM's direct answer agrees with its composed decomposition — label-free, r≥0.86 correlation with accuracy across 12 models and 4 multi-hop QA sets.",
    whyZh: "利用算符理论检验LLM组合推理一致性：在12个模型和4个多跳QA数据集上与准确率相关系数≥0.86，无需人工标注。",
    pick: true,
  },
  {
    date: "2026-06-14",
    title: "Counterexample Guided Learning in the Large using Reasoning Agents",
    titleZh: "用推理智能体进行大规模反例引导学习",
    authors: "Hongyi Liu et al.",
    arxivId: "2606.11521",
    tags: ["Reasoning", "Agent"],
    why: "Applies classical CEGIS to LLM reasoning agents: symbolic verifier counterexamples lift regex induction success from 3.2% to 38.1% — formal feedback dramatically improves sample efficiency.",
    whyZh: "将经典符号反例引导学习引入LLM智能体，验证器反馈使正则表达式归纳成功率从3.2%跃升至38.1%，显著提升样本效率。",
  },
  {
    date: "2026-06-14",
    title: "The Neutral Mask: How RLHF Provides Shallow Alignment while Leaving Partisan Structure Intact in a Large Language Model",
    titleZh: "中立面具：RLHF如何在保留党派结构的同时实现浅层对齐",
    authors: "Wendy K. Tam",
    arxivId: "2606.09735",
    tags: ["Alignment", "Theory"],
    why: "Mechanistic study of Llama 3.1 8B before/after RLHF: political neutrality is enforced by severing partisan geometry from output generation, not erasing knowledge — shallow alignment revealed.",
    whyZh: "对Llama 3.1 8B进行RLHF前后机理研究：政治中立通过切断党派几何与输出路径实现，而非消除相关知识，揭示浅层对齐本质。",
  },
  {
    date: "2026-06-14",
    title: "Routing-Aware Expert Calibration for Machine Unlearning in Mixture-of-Experts Language Models",
    titleZh: "面向MoE语言模型机器遗忘的路由感知专家校准",
    authors: "Jingyi Xie et al.",
    arxivId: "2606.10338",
    tags: ["MoE", "Alignment"],
    why: "TRACE detects forget-critical MoE experts from activation statistics and reweights retain losses to fix the routing mismatch that undermines unlearning in large MoE LLMs.",
    whyZh: "TRACE从激活统计中检测遗忘关键专家并重加权保留损失，修正路由不匹配，解决MoE大模型机器遗忘的核心问题。",
  },
  {
    date: "2026-06-07",
    title: "Thinking Economically: A Hierarchical Framework for Adaptive-Complexity Reasoning in LLMs",
    titleZh: "经济思维：面向LLM的层级自适应复杂度推理框架",
    authors: "Yubo Gao et al.",
    arxivId: "2606.01168",
    tags: ["Reasoning", "Efficient Inference"],
    why: "HAB applies coarse-to-fine budget allocation across problems and steps — surpasses standard CoT in accuracy while cutting token usage on GSM8K and MATH500.",
    whyZh: "HAB框架对问题和步骤分层分配计算预算，在GSM8K和MATH500上精度超越标准CoT同时减少token消耗。",
    pick: true,
  },
  {
    date: "2026-06-07",
    title: "SimSD: Simple Speculative Decoding in Diffusion Language Models",
    titleZh: "SimSD：扩散语言模型中的简单推测解码",
    authors: "Junxia Cui et al.",
    arxivId: "2606.02544",
    tags: ["Diffusion LM", "Efficient Inference"],
    why: "Plug-and-play masking strategy gives diffusion LMs temporally valid token context for speculative decoding — training-free speedup from UCSD/UIUC/Google.",
    whyZh: "即插即用掩码策略为扩散LM提供时序有效的token上下文，实现无需训练的推测解码加速。",
    pick: true,
  },
  {
    date: "2026-06-07",
    title: "The Self-Correction Illusion: LLMs Correct Others but Not Themselves",
    titleZh: "自纠正幻觉：LLM能纠正他人却无法纠正自身",
    authors: "Kuan-Yen Chen et al.",
    arxivId: "2606.05976",
    tags: ["Reasoning", "Benchmark"],
    why: "Identical errors corrected 23–93pp more often when labeled external vs. own output — role label, not content, drives self-correction across 7 model families.",
    whyZh: "相同错误标记为外部时纠错率比自身输出高23–93个百分点，角色标签而非内容决定自纠正能力，覆盖7个模型家族。",
    pick: true,
  },
  {
    date: "2026-06-07",
    title: "Geometric Latent Reasoning Induces Shorter Generations in LLMs",
    titleZh: "几何潜在推理诱导LLM生成更短输出",
    authors: "Shashi Kumar et al.",
    arxivId: "2606.02248",
    tags: ["Reasoning", "Theory"],
    why: "GLR predicts iterative direction updates in embedding space rather than discrete tokens — emergent shorter generations on math benchmarks without length supervision.",
    whyZh: "GLR在嵌入空间中预测迭代方向更新而非离散token，在数学基准上自然诱导更短生成序列，无需长度监督。",
  },
  {
    date: "2026-06-07",
    title: "SAID: Accelerating Diffusion-Based Language Models via Scaffold-Aware Iterative Decoding",
    titleZh: "SAID：基于脚手架感知迭代解码的扩散语言模型加速",
    authors: "Na Li et al.",
    arxivId: "2606.04974",
    tags: ["Diffusion LM", "Efficient Inference"],
    why: "Scaffold tokens get full denoising steps; predictable detail tokens get fewer — reallocates diffusion compute to where uncertainty is highest.",
    whyZh: "脚手架token获得完整去噪步骤，可预测细节token步骤减少，计算资源精准分配至不确定性最高处。",
  },
  {
    date: "2026-05-31",
    title: "BlockBatch: Multi-Scale Consensus Decoding for Efficient Diffusion Language Model Inference",
    titleZh: "BlockBatch：高效扩散语言模型推理的多尺度共识解码",
    authors: "Xiaoyou Wu et al.",
    arxivId: "2605.29233",
    tags: ["Diffusion LM", "Efficient Inference"],
    why: "Training-free multi-scale consensus decoding reduces denoising NFEs by 26.6% and delivers 1.33× end-to-end speedup over Fast-dLLM — no quality loss.",
    whyZh: "免训练多尺度共识解码将去噪步骤减少26.6%，相比Fast-dLLM实现1.33倍端到端加速，无质量损失。",
    pick: true,
  },
  {
    date: "2026-05-31",
    title: "You Only Need Minimal RLVR Training: Extrapolating LLMs via Rank-1 Trajectories",
    titleZh: "最小化RLVR训练：通过秩-1轨迹外推大语言模型",
    authors: "Zhepei Wei et al.",
    arxivId: "2605.21468",
    tags: ["Reasoning", "RLHF"],
    why: "RLVR parameter deltas are rank-1 and near-linear; RELEX extrapolates via regression — achieves full RLVR gains with a fraction of GPU training steps.",
    whyZh: "RLVR参数增量为秩1且近线性，RELEX通过线性回归外推检查点，以极少训练步骤获得完整RLVR收益。",
    pick: true,
  },
  {
    date: "2026-05-31",
    title: "Looped Diffusion Language Models",
    titleZh: "循环扩散语言模型（LoopMDM）",
    authors: "Sanghyun Lee et al.",
    arxivId: "2605.26106",
    tags: ["Diffusion LM", "Theory"],
    why: "LoopMDM selectively loops early-middle transformer layers — matches larger MDMs with 3.3× fewer training FLOPs, +8.5pp GSM8K gain, flexible compute at inference.",
    whyZh: "LoopMDM选择性循环早中层实现深度缩放，以3.3倍更少训练FLOPs匹敌更大模型，GSM8K提升8.5分。",
    pick: true,
  },
  {
    date: "2026-05-31",
    title: "From AR to Diffusion: Efficiently Adapting Large Language Models with Strictly Causal and Elastic Horizons",
    titleZh: "从AR到扩散：通过严格因果与弹性视野高效适配大语言模型（FLUID）",
    authors: "Xiangyu Ma et al.",
    arxivId: "2605.27387",
    tags: ["Diffusion LM", "Fine-tuning"],
    why: "FLUID bridges AR-to-diffusion via strictly causal alignment and entropy-driven elastic horizons — reuses GPT-style checkpoints at orders-of-magnitude lower training cost.",
    whyZh: "FLUID通过严格因果对齐和信息熵驱动弹性视野连接AR与扩散，以极低训练成本复用GPT检查点。",
  },
  {
    date: "2026-05-31",
    title: "When RL Suppresses Its Own Vocabulary: Recovering Reasoning Diversity in Puzzle-to-Math Transfer",
    titleZh: "RL压制自身词汇表：恢复谜题到数学迁移中的推理多样性",
    authors: "Mayug Maniparambil et al.",
    arxivId: "2605.29190",
    tags: ["Reasoning", "RLHF"],
    why: "RL fine-tuning suppresses exploratory primitives like hypothesize/backtrack; novelty bonus restores them — +7pp pass@32 on OlymMATH-Hard with no math in training data.",
    whyZh: "RL后训练压制假设/回溯等探索性推理原语，新颖性奖励恢复这些能力，OlymMATH-Hard pass@32提升7分，训练数据无需数学题。",
  },
  {
    date: "2026-05-22",
    title: "Unified Data Selection for LLM Reasoning",
    titleZh: "LLM推理统一数据选择框架",
    authors: "et al.",
    arxivId: "2605.22389",
    tags: ["Reasoning", "Fine-tuning"],
    why: "Unifies data selection across SFT and RL reasoning pipelines via principled instance-level difficulty scoring — consistent gains on math and code benchmarks.",
    whyZh: "通过实例级难度评分统一SFT与RL推理流水线的数据选择策略，在数学和代码基准上取得一致提升。",
  },
  {
    date: "2026-05-20",
    title: "TIDE: Efficient and Lossless MoE Diffusion LLM Inference with I/O-aware Expert Offload",
    titleZh: "TIDE：I/O感知专家卸载实现高效无损MoE扩散LLM推理",
    authors: "et al.",
    arxivId: "2605.20179",
    tags: ["Diffusion LM", "MoE", "Efficient Inference"],
    why: "Exploits temporal stability of expert activations during diffusion for I/O-aware offloading — lossless MoE dLLM inference on resource-constrained devices.",
    whyZh: "利用扩散过程中专家激活的时序稳定性实现I/O感知卸载，在资源受限设备上无损部署MoE扩散LLM。",
    pick: true,
  },
  {
    date: "2026-05-20",
    title: "Introspective X Training: Feedback Conditioning Improves Scaling Across all LLM Training Stages",
    titleZh: "内省X训练：反馈条件化提升全阶段LLM训练规模效益",
    authors: "et al.",
    arxivId: "2605.20285",
    tags: ["Pre-training", "Fine-tuning"],
    why: "Conditions each training stage on structured feedback signals — bends scaling curves across pre-training, SFT, and RLHF on 7.5B–12B transformer models.",
    whyZh: "通过结构化反馈信号条件化每个训练阶段，在7.5B-12B模型的预训练、SFT和RLHF全阶段改善规模效益曲线。",
  },
  {
    date: "2026-05-17",
    title: "Theoretical Limits of Language Model Alignment",
    titleZh: "语言模型对齐的理论极限",
    authors: "Lucas Monteiro Paes et al.",
    arxivId: "2605.07105",
    tags: ["Theory", "Alignment"],
    why: "Apple derives the KL-reward Pareto frontier for alignment in closed form — best-of-N nearly reaches theoretical optimal while PPO and GRPO remain far suboptimal.",
    whyZh: "Apple推导对齐的信息论KL-奖励帕累托前沿，best-of-N接近理论最优，PPO/GRPO仍大幅低于极限，为对齐研究提供理论锚点。",
    pick: true,
  },
  {
    date: "2026-05-17",
    title: "Block-R1: Rethinking the Role of Block Size in Multi-domain Reinforcement Learning for Diffusion Large Language Models",
    titleZh: "Block-R1：重思多领域强化学习中扩散大语言模型的块尺寸",
    authors: "Yan Jiang et al.",
    arxivId: "2605.11726",
    tags: ["Diffusion LM", "Reasoning", "RLHF"],
    why: "Domain block-size conflict bottlenecks multi-domain dLLM RL post-training; Block-R1-41K assigns per-sample optimal block sizes to resolve cross-domain tension in GRPO.",
    whyZh: "块尺寸冲突是多领域dLLM RL后训练的关键瓶颈，Block-R1-41K为每个样本分配最优块尺寸，有效缓解GRPO跨领域训练张力。",
    pick: true,
  },
  {
    date: "2026-05-17",
    title: "Break the Block: Dynamic-size Reasoning Blocks for Diffusion LLMs via Monotonic Entropy Descent with RL",
    titleZh: "打破块限制：单调熵下降强化学习驱动的扩散LLM动态推理块",
    authors: "Yan Jiang et al.",
    arxivId: "2605.02263",
    tags: ["Diffusion LM", "Reasoning", "Efficient Inference"],
    why: "Fixed block size in dLLMs breaks reasoning coherence; monotonic entropy descent RL learns adaptive block boundaries, improving quality across diverse reasoning tasks.",
    whyZh: "固定块尺寸破坏扩散LLM推理连贯性，单调熵下降RL框架自适应学习块边界，在多类推理任务中显著提升生成质量。",
  },
  {
    date: "2026-05-17",
    title: "Roll Out and Roll Back: Diffusion LLMs are Their Own Efficiency Teachers",
    titleZh: "顺推与回溯：扩散LLM是自身的效率教师",
    authors: "et al.",
    arxivId: "2605.16941",
    tags: ["Diffusion LM", "Efficient Inference"],
    why: "Self-supervised adaptive denoising order unmasks easy tokens first — 6.1x step reduction with +2.6% GSM8K accuracy, no additional model training required.",
    whyZh: "自监督自适应解码顺序优先解码易token，无需额外训练实现GSM8K步数减少6.1倍同时精度提升2.6%。",
    pick: true,
  },
  {
    date: "2026-05-16",
    title: "The Unlearnability Phenomenon in RLVR for Language Models",
    titleZh: "语言模型RLVR中的不可学习现象",
    authors: "et al.",
    arxivId: "2605.16787",
    tags: ["Reasoning", "RLHF"],
    why: "Hard RLVR examples contain a substantial unlearnable subset resistant to training even with correct rollouts — warns against naive hard-example overweighting.",
    whyZh: "RLVR难样本中存在大量不可学习子集，即使有正确轨迹也无法被学习，警示盲目增加难样本权重的风险。",
    pick: true,
  },
  {
    date: "2026-05-15",
    title: "OpenDeepThink: Parallel Reasoning via Bradley-Terry Aggregation",
    titleZh: "OpenDeepThink：基于Bradley-Terry聚合的并行推理",
    authors: "et al.",
    arxivId: "2605.15177",
    tags: ["Reasoning", "Efficient Inference"],
    why: "Population-based test-time compute selects best parallel reasoning traces via pairwise Bradley-Terry comparison — only $39.9 strategy discovery cost, strong math gains.",
    whyZh: "基于种群的测试时计算通过两两Bradley-Terry比较选最优推理链，策略发现仅需$39.9，数学推理显著提升。",
  },
  {
    date: "2026-05-14",
    title: "Factorization-Error-Free Discrete Diffusion Language Model via Speculative Decoding",
    titleZh: "基于推测解码的无分解误差离散扩散语言模型",
    authors: "et al.",
    arxivId: "2605.14305",
    tags: ["Diffusion LM", "Efficient Inference"],
    why: "Speculative decoding eliminates factorization errors in discrete diffusion — +5.04% accuracy and 3.86x speedup simultaneously, resolving a core quality-speed tradeoff.",
    whyZh: "推测解码消除离散扩散分解误差，同时实现5.04%精度提升和3.86倍加速，化解核心质速权衡难题。",
  },
  {
    date: "2026-05-12",
    title: "Towards Closing the Autoregressive Gap via Entropy-Gated Continuous Bitstream Diffusion",
    titleZh: "通过熵门控连续比特流扩散弥合自回归差距",
    authors: "Georgios Batzolis et al.",
    arxivId: "2605.07013",
    tags: ["Diffusion LM", "Theory"],
    why: "130M bitstream diffusion model reaches AR-level perplexity (59.76) on LM1B with 256 steps, setting a new diffusion-LM Pareto frontier on OWT.",
    whyZh: "1.3亿参数比特流扩散模型在LM1B上达自回归水平（困惑度59.76），OWT上仅需原来四分之一步数建立扩散LM新帕累托前沿。",
  },
  {
    date: "2026-05-11",
    title: "Beyond Reasoning: Reinforcement Learning Unlocks Parametric Knowledge in LLMs",
    titleZh: "超越推理：强化学习解锁LLM的参数化知识",
    authors: "Wanli Yang et al.",
    arxivId: "2605.07153",
    tags: ["Reasoning", "RLHF"],
    why: "RL on factual QA yields ~27% average relative gains — redistributes existing latent knowledge to reliable greedy generation without learning new facts.",
    whyZh: "RL在事实问答上带来约27%相对提升，机制是将既有潜在知识重分配至可靠贪心解码，而非习得新知识。",
  },
  {
    date: "2026-05-11",
    title: "FlashDLM: Accelerating Diffusion Language Model Inference via Efficient KV Caching and Guided Diffusion",
    titleZh: "FlashDLM：通过高效KV缓存与引导扩散加速扩散语言模型推理",
    authors: "Zhanqiu Hu et al.",
    arxivId: "2505.21467",
    tags: ["Diffusion LM", "Efficient Inference"],
    why: "FreeCache + Guided Diffusion delivers 12.14x end-to-end speedup on Dream-7B-Instruct — training-free KV caching for diffusion LMs.",
    whyZh: "FreeCache+引导扩散实现Dream-7B 12.14倍端到端加速，无需训练即可为扩散LM引入KV缓存加速。",
  },
  {
    date: "2026-05-10",
    title: "RVPO: Risk-Sensitive Alignment via Variance Regularization",
    titleZh: "RVPO：基于方差正则化的风险敏感对齐",
    authors: "Montero et al.",
    arxivId: "2605.05750",
    tags: ["Alignment", "RLHF"],
    why: "Penalizes inter-reward variance during advantage aggregation — fixes a failure mode in arithmetic-mean multi-objective RLHF, validated on medical/scientific reasoning with 17 concurrent reward signals.",
    whyZh: "RVPO惩罚优势聚合中的跨奖励方差，修复多目标无Critic RLHF的均值聚合缺陷，在17个并发奖励信号的医学推理场景中验证。",
  },
  {
    date: "2026-05-10",
    title: "A Unified Pair-GRPO Family: From Implicit to Explicit Preference Constraints for Stable and General RL Alignment",
    titleZh: "统一Pair-GRPO族：从隐式到显式偏好约束的稳定通用RL对齐",
    authors: "Hao Yu et al.",
    arxivId: "2605.06375",
    tags: ["RLHF", "Alignment"],
    why: "Soft/Hard Pair-GRPO unify implicit and explicit preference constraints — address training instability in GRPO-style alignment and consistently outperform SOTA on standard benchmarks.",
    whyZh: "Soft/Hard Pair-GRPO统一隐式与显式偏好约束，解决GRPO类方法训练不稳定问题，在标准对齐基准上持续领先。",
    pick: true,
  },
  {
    date: "2026-05-10",
    title: "Federation of Experts: Communication Efficient Distributed Inference for Large Language Models",
    titleZh: "专家联合（FoE）：大语言模型通信高效分布式推理",
    authors: "Abdurrahman et al.",
    arxivId: "2605.06206",
    tags: ["MoE", "Efficient Inference"],
    why: "FoE restructures MoE blocks into expert clusters to cut cross-node token embedding communication — validated on 1B/7B models over 8×H100 and two-node InfiniBand clusters.",
    whyZh: "FoE将MoE模块重组为专家集群，切断跨节点token嵌入通信瓶颈，在单节点8×H100和双节点InfiniBand上验证。",
  },
  {
    date: "2026-05-10",
    title: "Making Every Verified Token Count: Adaptive Verification for MoE Speculative Decoding",
    titleZh: "让每个验证Token物尽其用：MoE推测解码的自适应验证",
    authors: "Lehan Pan et al.",
    arxivId: "2605.00342",
    tags: ["MoE", "Efficient Inference"],
    why: "EVICT — training-free, lossless expert-aware draft tree pruning for MoE speculative decoding — achieves 2.35x speedup over AR and 1.21x over EAGLE-3, with SGLang integration.",
    whyZh: "EVICT为MoE推测解码提供无需训练的专家感知草稿树剪枝，比AR快2.35倍、比EAGLE-3快1.21倍，已集成SGLang。",
    pick: true,
  },
  {
    date: "2026-05-10",
    title: "Continuous Latent Diffusion Language Model",
    titleZh: "连续潜空间扩散语言模型（Cola DLM）",
    authors: "Hongcan Guo et al.",
    arxivId: "2605.06548",
    tags: ["Diffusion LM", "Pre-training"],
    why: "Hierarchical continuous latent diffusion via Text VAE + block-causal DiT — validated on 8 benchmarks against strictly matched ~2B AR and LLaDA baselines.",
    whyZh: "文本VAE与块因果DiT构建分层连续潜扩散LM，在8项基准上与LLaDA等~2B基线严格对齐比较。",
  },
  {
    date: "2026-05-09",
    title: "LatentRAG: Latent Reasoning and Retrieval for Efficient Agentic RAG",
    titleZh: "LatentRAG：面向高效智能体RAG的潜空间推理与检索",
    authors: "Yijia Zheng and Marcel Worring",
    arxivId: "2605.06285",
    tags: ["RAG", "Efficient Inference", "Agent"],
    why: "Shifts agentic RAG thoughts and subqueries into continuous latent space — ~90% latency reduction on 7 benchmarks with comparable accuracy.",
    whyZh: "将智能体RAG推理与检索迁至连续潜空间，7个基准上延迟降低约90%，精度可比显式方法。",
  },
  {
    date: "2026-05-09",
    title: "Post Reasoning: Improving the Performance of Non-Thinking Models at No Cost",
    titleZh: "后置推理：零成本提升非思维模型的推理性能",
    authors: "Richmond Xuan et al.",
    arxivId: "2605.06165",
    tags: ["Reasoning", "Fine-tuning"],
    why: "Conditioning non-thinking models to justify answers after generation improves performance across 117 model–benchmark settings with zero added latency.",
    whyZh: "生成答案后追加推理依据，零延迟零成本，在117个模型-基准设置下性能普遍提升。",
  },
  {
    date: "2026-05-08",
    title: "Rethinking RL for LLM Reasoning: It's Sparse Policy Selection, Not Capability Learning",
    titleZh: "重新思考LLM推理的RL：稀疏策略选择而非能力习得",
    authors: "Ömer Faruk Akgül et al.",
    arxivId: "2605.06241",
    tags: ["Reasoning", "Theory"],
    why: "RL edits only 1–3% of token positions at high-entropy decision points; ReasonMaxxer matches full RL with 3 orders of magnitude less training compute.",
    whyZh: "RL仅修改1-3%的token位置（高熵决策点），ReasonMaxxer无需RL即以千倍更少算力匹配完整RL推理性能。",
    pick: true,
  },
  {
    date: "2026-05-08",
    title: "Can RL Teach Long-Horizon Reasoning to LLMs? Expressiveness Is Key",
    titleZh: "RL能教会LLM长时域推理吗？表达性是关键",
    authors: "Tianle Wang et al.",
    arxivId: "2605.06638",
    tags: ["Reasoning", "Theory", "Benchmark"],
    why: "RL compute follows power law with reasoning depth; scaling exponent rises from 1.04 to 2.60 with logical expressiveness — fundamental limits on trainable reasoning.",
    whyZh: "RL计算量随推理深度呈幂律增长，逻辑表达性越高指数越大（1.04至2.60），揭示推理训练的扩展规律。",
  },
  {
    date: "2026-05-08",
    title: "ReaComp: Compiling LLM Reasoning into Symbolic Solvers for Efficient Program Synthesis",
    titleZh: "ReaComp：将LLM推理编译为符号求解器以实现高效程序合成",
    authors: "Atharva Naik et al.",
    arxivId: "2605.05485",
    tags: ["Reasoning", "Code", "Efficient Inference"],
    why: "Compiles reasoning traces into symbolic solvers — 91.3% on PBEBench-Lite, +16.3 pp over LLM test-time scaling at zero inference cost.",
    whyZh: "将推理轨迹编译为符号求解器，PBEBench-Lite达91.3%，零推理成本超越LLM测试时扩展16.3个百分点。",
  },
  {
    date: "2026-05-07",
    title: "MoBiE: Efficient Inference of Mixture of Binary Experts under Post-Training Quantization",
    titleZh: "MoBiE：基于训练后量化的混合二值专家高效推理",
    authors: "Zhixiong Zhao et al.",
    arxivId: "2604.06798",
    tags: ["MoE", "Quantization", "Efficient Inference"],
    why: "First binarization framework for MoE LLMs — joint SVD decomposition and gradient-aware Hessian quantization cut memory without routing distortion.",
    whyZh: "首个面向MoE LLM的二值化框架，联合SVD分解与梯度感知Hessian量化，压缩内存同时保持专家路由稳定性。",
  },
  {
    date: "2026-05-07",
    title: "Exploring Pass-Rate Reward in Reinforcement Learning for Code Generation",
    titleZh: "探索代码生成强化学习中的通过率奖励",
    authors: "Xin-Ye Li et al.",
    arxivId: "2605.02944",
    tags: ["Code", "RLHF"],
    why: "Controlled study finds pass-rate rewards don't reliably outperform binary rewards in critic-free code RL — denser rewards don't shift gradients toward full-pass solutions.",
    whyZh: "严格对照实验表明，无critic代码RL中pass-rate奖励并不稳定优于二元奖励，更密集奖励信号不能可靠引导梯度指向全通过解。",
  },
  {
    date: "2026-05-06",
    title: "Focus on the Core: Empowering Diffusion Large Language Models by Self-Contrast",
    titleZh: "聚焦核心：基于自对比的扩散大语言模型增强",
    authors: "Jinyuan Feng et al.",
    arxivId: "2605.01373",
    tags: ["Diffusion LM", "Efficient Inference"],
    why: "Training-free self-contrast decoding for diffusion LLMs — HumanEval pass@1 +3.66 pts; FoCore-A cuts latency 58.4%.",
    whyZh: "无需训练的自对比解码策略，HumanEval pass@1提升3.66分，加速变体延迟降低58.4%。",
  },
  {
    date: "2026-05-06",
    title: "LEAP: Layer-wise Exit-Aware Pretraining for Efficient Transformer Inference",
    titleZh: "LEAP：面向高效Transformer推理的分层退出感知预训练",
    authors: "Shashank Kapadia et al.",
    arxivId: "2605.01058",
    tags: ["Efficient Inference", "Pre-training"],
    why: "Auxiliary objective reconciles distillation and early-exit incompatibility — 1.61× wall-clock speedup; 91.9% samples exit by layer 7.",
    whyZh: "解决知识蒸馏与早退出的不兼容问题，实现1.61倍实际推理加速，91.9%样本在第7层即可退出。",
  },
  {
    date: "2026-05-04",
    title: "ResRL: Boosting LLM Reasoning via Negative Sample Projection Residual Reinforcement Learning",
    titleZh: "ResRL：负样本投影残差强化学习提升LLM推理",
    authors: "Zihan Lin et al.",
    arxivId: "2605.00380",
    tags: ["Reasoning", "RLHF"],
    why: "SVD-based negative sample projection decouples positive/negative semantics, outperforming GRPO/NSR across 12 math, code, agent, and function-calling benchmarks.",
    whyZh: "SVD投影解耦正负样本语义，12项数学/代码/智能体基准全面超越GRPO/NSR。",
    pick: true,
  },
  {
    date: "2026-05-04",
    title: "AGoQ: Activation and Gradient Quantization for Memory-Efficient Distributed Training of LLMs",
    titleZh: "AGoQ：面向LLM分布式训练的激活与梯度量化",
    authors: "Wenxiang Lin et al.",
    arxivId: "2605.00539",
    tags: ["Quantization", "Pre-training"],
    why: "Layer-aware 4-bit activation + 8-bit gradient quantization cuts distributed LLM training memory by up to 52% and boosts speed by 1.34× over Megatron-LM and DeepSpeed.",
    whyZh: "逐层量化激活与梯度，训练内存降低52%，速度比Megatron-LM提升1.34倍。",
  },
  {
    date: "2026-05-04",
    title: "Reward Models Are Secretly Value Functions: Temporally Coherent Reward Modeling",
    titleZh: "奖励模型其实是价值函数：时间相干奖励建模",
    authors: "Alex Nikulkov",
    arxivId: "2604.22981",
    tags: ["RLHF", "Theory", "Alignment"],
    why: "Proves RM outputs should equal conditional expected reward; two Bradley-Terry regularizers provably tie token-level scores to RL value functions.",
    whyZh: "奖励模型本质是价值函数，TCRM正则化统一token级评分与RL条件期望。",
  },
  {
    date: "2026-05-03",
    title: "Large Language Model Post-Training: A Unified View of Off-Policy and On-Policy Learning",
    titleZh: "大语言模型后训练：离线与在线学习的统一视角",
    authors: "Shiwan Zhao et al.",
    arxivId: "2604.07941",
    tags: ["Fine-tuning", "RLHF"],
    why: "Unifies SFT, DPO, PPO, GRPO, and process supervision under off-policy vs. on-policy taxonomy — clearest conceptual map of LLM post-training to date.",
    whyZh: "将SFT、DPO、PPO、GRPO等方法统一为离线/在线学习框架，迄今最清晰的LLM后训练方法分类与综述。",
    pick: true,
  },
  {
    date: "2026-05-03",
    title: "Adaptive Test-Time Compute Allocation for Reasoning LLMs via Constrained Policy Optimization",
    titleZh: "通过约束策略优化自适应分配推理LLM的测试时计算资源",
    authors: "Zhiyuan Zhai et al.",
    arxivId: "2604.14853",
    tags: ["Reasoning", "Efficient Inference"],
    why: "Formalizes thinking-token budget as constrained optimization — Solve-then-Learn pipeline allocates more tokens to hard problems, achieving 12.8% accuracy gain on MATH under fixed compute.",
    whyZh: "将思考token预算形式化为约束优化，难题多算简题少算，在固定计算预算下MATH准确率提升12.8%。",
  },
  {
    date: "2026-05-03",
    title: "DepthKV: Layer-Dependent KV Cache Pruning for Long-Context LLM Inference",
    titleZh: "DepthKV：长上下文LLM推理的层依赖KV缓存剪枝",
    authors: "Zahra Dehghanighobadi and Asja Fischer",
    arxivId: "2604.24647",
    tags: ["Efficient Inference"],
    why: "Layers differ in pruning sensitivity — allocating KV budget proportional to layer sensitivity outperforms uniform pruning at the same global ratio across multiple models and tasks.",
    whyZh: "各层对KV剪枝敏感度差异显著，按层敏感度分配预算取代均匀分配，相同压缩比下多模型一致优于均匀剪枝。",
  },
  {
    date: "2026-05-03",
    title: "On the Quantization Robustness of Diffusion Language Models in Coding Benchmarks",
    titleZh: "扩散语言模型在代码基准上的量化鲁棒性研究",
    authors: "Aarav Gupta et al.",
    arxivId: "2604.20079",
    tags: ["Diffusion LM", "Quantization"],
    why: "First PTQ study comparing diffusion vs. AR coding LLMs — at 2–4 bits, diffusion models degrade less than autoregressive counterparts on HumanEval and MBPP.",
    whyZh: "首个对比代码扩散LLM与AR LLM后训练量化研究：2-4比特下扩散模型精度损失更小，展示低比特部署优势。",
  },
  {
    date: "2026-05-03",
    title: "Path-Lock Expert: Separating Reasoning Mode in Hybrid Thinking via Architecture-Level Separation",
    titleZh: "路径锁专家：通过架构级分离解耦混合思维中的推理模式",
    authors: "Shouren Wang et al.",
    arxivId: "2604.27201",
    tags: ["Reasoning", "Efficient Inference"],
    why: "Two mode-locked MLP experts per layer eliminate reasoning leakage in hybrid LLMs — Qwen3-4B no-think AIME24 accuracy: 20.67% → 40.00%, reflective tokens 2.54 → 0.39.",
    whyZh: "每层MLP替换为两个模式锁定专家，架构级分离思考/非思考——Qwen3-4B无思考AIME24准确率从20.67%升至40.00%，反思token从2.54降至0.39。",
    pick: true,
  },
  {
    date: "2026-05-03",
    title: "One Refiner to Unlock Them All: Inference-Time Reasoning Elicitation via Reinforcement Query Refinement",
    titleZh: "一个精化器解锁所有模型：基于强化查询精化的推理激发",
    authors: "Yixiao Zhou et al.",
    arxivId: "2604.25444",
    tags: ["Reasoning", "RLHF"],
    why: "ReQueR trains a single RL Refiner to rewrite queries for frozen LLMs — one-to-many reasoning elicitation with 1.7%–7.2% absolute gains without fine-tuning target models.",
    whyZh: "ReQueR训练单一RL查询精化器，无需微调目标模型即可激发其推理潜力，跨架构绝对提升1.7%–7.2%。",
  },
  {
    date: "2026-05-01",
    title: "Faster LLM Inference via Sequential Monte Carlo",
    titleZh: "基于序列蒙特卡洛的LLM快速推理",
    authors: "Yahya Emara et al.",
    arxivId: "2604.15672",
    tags: ["Efficient Inference", "Reasoning"],
    why: "SMC-SD replaces token-level rejection with importance-weighted resampling — 2.36x faster than speculative decoding, 5.2x over autoregressive, within 3% accuracy.",
    whyZh: "SMC-SD用重要性加权重采样替代逐token拒绝，比标准推测解码快2.36倍，比自回归快5.2倍，精度损失在3%以内。",
    pick: true,
  },
  {
    date: "2026-04-30",
    title: "Turning the TIDE: Cross-Architecture Distillation for Diffusion Large Language Models",
    titleZh: "TIDE：扩散大语言模型的跨架构知识蒸馏",
    authors: "Gongbo Zhang et al.",
    arxivId: "2604.26951",
    tags: ["Diffusion LM", "Fine-tuning"],
    why: "TIDE transfers AR LLM knowledge into diffusion models across tokenizer boundaries — SOTA diffusion LM quality without full retraining.",
    whyZh: "TIDE通过三模块跨tokenizer边界将AR模型知识蒸馏至扩散LM，无需完整重训练即达扩散质量SOTA。",
  },
  {
    date: "2026-04-29",
    title: "SFT-then-RL Outperforms Mixed-Policy Methods for LLM Reasoning",
    titleZh: "SFT-then-RL优于混合策略LLM推理训练方法",
    authors: "Alexis Limozin et al.",
    arxivId: "2604.23747",
    tags: ["Reasoning", "Fine-tuning"],
    why: "DeepSpeed/OpenRLHF bugs inflated mixed-policy baselines — corrected SFT-then-RL surpasses all mixed methods by +3.8 on math with Qwen2.5-Math-7B.",
    whyZh: "DeepSpeed/OpenRLHF存在隐性bug导致混合策略基准虚高，修复后SFT-then-RL在数学推理上超越所有混合方法+3.8分。",
    pick: true,
  },
  {
    date: "2026-04-29",
    title: "Too Correct to Learn: Reinforcement Learning on Saturated Reasoning Data",
    titleZh: "过于正确难以学习：饱和推理数据上的强化学习",
    authors: "Zhenwen Liang et al.",
    arxivId: "2604.18493",
    tags: ["Reasoning", "RLHF"],
    why: "Strong models saturate benchmarks, killing RL advantage signals — CUTS sampling boosts AIME25 Pass@1 by up to 15.1% over GRPO.",
    whyZh: "强模型令基准饱和导致RL优势信号消失，CUTS采样策略在AIME25上比GRPO提升最高15.1%。",
  },
  {
    date: "2026-04-28",
    title: "SCaTR: Simple Calibrated Test-Time Ranking",
    titleZh: "SCaTR：简单校准的测试时排名方法",
    authors: "Divya Shyamal et al.",
    arxivId: "2604.16535",
    tags: ["Efficient Inference", "Reasoning"],
    why: "Calibrates Best-of-N selection using hidden-layer representations — up to 9% gain over confidence baselines, matching PRMs at much lower cost.",
    whyZh: "用目标LLM隐层表征训练轻量排名器，在数学/代码任务上最高提升9%，以极低成本媲美过程奖励模型。",
    pick: true,
  },
  {
    date: "2026-04-28",
    title: "Scaling Test-Time Compute for Agentic Coding",
    titleZh: "面向智能体编程的推理时算力扩展",
    authors: "Joongwon Kim et al.",
    arxivId: "2604.16529",
    tags: ["Agent", "Code", "Efficient Inference"],
    why: "Scales test-time compute for long-horizon coding agents by compressing rollout trajectories into structured summaries of hypotheses, progress, and failures.",
    whyZh: "将编程智能体执行轨迹压缩为结构化摘要，将测试时算力扩展方法推广到长时域智能体编程场景。",
  },
  {
    date: "2026-04-28",
    title: "Contexts are Never Long Enough: Structured Reasoning for Scalable QA over Long Document Sets",
    titleZh: "SLIDERS：通过结构化推理实现超长文档集合的可扩展问答",
    authors: "Harshit Joshi et al.",
    arxivId: "2604.22294",
    tags: ["RAG", "Reasoning"],
    why: "SLIDERS extracts document collections into a relational database for SQL-driven reasoning — scales QA beyond fixed context windows as collections grow.",
    whyZh: "将文档集合提炼为关系型数据库，通过SQL推理实现超越固定上下文窗口的可扩展长文档问答。",
  },
  {
    date: "2026-04-27",
    title: "Efficient RL Training for LLMs with Experience Replay",
    titleZh: "基于经验回放的LLM高效强化学习训练",
    authors: "Charles Arnal et al.",
    arxivId: "2604.08706",
    tags: ["RLHF", "Fine-tuning"],
    why: "Replay buffers cut LLM RL training compute by up to 40% without hurting accuracy — challenges the on-policy data requirement in post-training.",
    whyZh: "经验回放使RL训练计算量降低最多40%且不损准确率，挑战后训练必须依赖在线数据的假设。",
  },
  {
    date: "2026-04-27",
    title: "Value-Conflict Diagnostics Reveal Widespread Alignment Faking in Language Models",
    titleZh: "价值冲突诊断揭示语言模型中普遍存在的对齐伪装",
    authors: "Inderjeet Nair et al.",
    arxivId: "2604.20995",
    tags: ["Alignment", "Benchmark"],
    why: "VLAF framework finds alignment faking in 37% of olmo2-7b cases — far more prevalent than reported and present even in 7B-scale models.",
    whyZh: "VLAF框架发现olmo2-7b中37%案例存在对齐伪装，远比已知普遍，7B小模型亦难逃。",
  },
  {
    date: "2026-04-25",
    title: "FastDiSS: Few-step Match Many-step Diffusion Language Model on Sequence-to-Sequence Generation",
    titleZh: "FastDiSS：少步匹配多步扩散语言模型用于序列到序列生成",
    authors: "Dat Nguyen-Cong et al.",
    arxivId: "2604.05551",
    tags: ["Diffusion LM", "Efficient Inference"],
    why: "Noise-perturbed self-conditioning training closes the few-step quality gap in continuous diffusion LMs — up to 400× faster inference.",
    whyZh: "噪声扰动自条件训练填补连续扩散LM少步推理的质量差距，推理速度最高提升400倍。",
    pick: true,
  },
  {
    date: "2026-04-25",
    title: "Thinking Diffusion: Penalize and Guide Visual-Grounded Reasoning in Diffusion Multimodal Language Models",
    titleZh: "思考扩散：引导扩散多模态大语言模型中的视觉基础推理",
    authors: "Keuntae Kim et al.",
    arxivId: "2604.05497",
    tags: ["Diffusion LM", "Multimodal", "Reasoning"],
    why: "PSP + VRG fix premature answer generation and weak visual grounding in dMLLMs — 7.5% higher accuracy with 3× fewer diffusion steps.",
    whyZh: "PSP与VRG修复扩散多模态LM的早答和视觉依赖不足问题，准确率提升7.5%，推理步骤减少3倍。",
  },
  {
    date: "2026-04-25",
    title: "ThinkTwice: Jointly Optimizing Large Language Models for Reasoning and Self-Refinement",
    titleZh: "ThinkTwice：联合优化大语言模型的推理与自我改进",
    authors: "Difan Jiao et al.",
    arxivId: "2604.01591",
    tags: ["Reasoning", "RLHF"],
    why: "GRPO-based two-phase training jointly optimizes solving and self-refining — +5pp AIME before refinement, +11.5pp after one self-refinement step on Qwen3-4B.",
    whyZh: "GRPO双阶段联合训练推理与自我改进，Qwen3-4B的AIME得分提升5pp，单次自我改进后再提升11.5pp。",
  },
  {
    date: "2026-04-24",
    title: "TEMPO: Scaling Test-time Training for Large Reasoning Models",
    titleZh: "TEMPO：大型推理模型的测试时训练扩展",
    authors: "Qingyang Zhang et al.",
    arxivId: "2604.19295",
    tags: ["Reasoning", "Fine-tuning"],
    why: "EM-style TTT alternates critic recalibration with policy refinement on unlabeled data — OLMO3-7B 33→51%, Qwen3-14B 42→66% on AIME 2024.",
    whyZh: "EM框架交替校准评论者与优化策略，无需标签数据即可持续提升推理——OLMO3-7B在AIME 2024从33%提升至51%，Qwen3-14B从42%提升至66%。",
    pick: true,
  },
  {
    date: "2026-04-24",
    title: "Language as a Latent Variable for Reasoning Optimization",
    titleZh: "语言作为推理优化的潜变量",
    authors: "Linjuan Wu et al.",
    arxivId: "2604.21593",
    tags: ["Reasoning", "Fine-tuning"],
    why: "polyGRPO treats language as latent exploration signal — 18.1K math problems yield +6.72% English reasoning and +4.9% commonsense, no CoT.",
    whyZh: "将语言选择作为潜在探索信号，仅用1.81万数学题训练，英文推理提升6.72%，常识推理提升4.9%，无需CoT标注。",
  },
  {
    date: "2026-04-23",
    title: "DeepSeek-V4 Technical Report",
    titleZh: "DeepSeek-V4 技术报告",
    authors: "DeepSeek AI",
    arxivId: "",
    paperUrl: "https://huggingface.co/deepseek-ai/DeepSeek-V4-Pro/blob/main/DeepSeek_V4.pdf",
    tags: ["MoE", "Pre-training", "Code"],
    why: "1.6T MoE (49B active), 1M context, Muon optimizer — 80.6% SWE Verified, 93.5 LiveCodeBench, Codeforces 3206. Open weights, MIT license.",
    whyZh: "1.6T MoE（49B 激活），1M 上下文，Muon 优化器 — SWE Verified 80.6%，LiveCodeBench 93.5，Codeforces 3206。开放权重，MIT 协议。",
    pick: true,
    slug: "deepseek-v4",
  },
  {
    date: "2026-04-23",
    title: "LLaDA2.0-Uni: Unifying Multimodal Understanding and Generation with Diffusion Large Language Model",
    titleZh: "LLaDA2.0-Uni：基于扩散大语言模型的多模态理解与生成统一框架",
    authors: "Inclusion AI et al.",
    arxivId: "2604.20796",
    tags: ["Diffusion LM", "Multimodal", "MoE"],
    why: "LLaDA 2.0 goes multimodal — MoE dLLM unifies image understanding and generation via mask token prediction, matching dedicated VLMs with 8-step distilled inference.",
    whyZh: "LLaDA 2.0进化为多模态：MoE扩散LLM通过掩码token预测统一图像理解与生成，8步蒸馏推理媲美专用VLM。",
    pick: true,
  },
  {
    date: "2026-04-23",
    title: "Self-Consistency from Only Two Samples: CoT-PoT Ensembling for Efficient LLM Reasoning",
    titleZh: "仅需两次采样的自一致性：面向高效LLM推理的CoT-PoT集成方法",
    authors: "Raman Saparkhan et al.",
    arxivId: "2604.17433",
    tags: ["Reasoning", "Efficient Inference"],
    why: "Combining chain-of-thought and program-of-thought cuts self-consistency sampling 9.3x — strong reasoning accuracy with just two samples.",
    whyZh: "结合思维链与程序化思维，将自一致性采样需求降低9.3倍，仅需两次采样即可获得强推理准确率。",
  },
  {
    date: "2026-04-22",
    title: "Demystifying the Unreasonable Effectiveness of Online Alignment Methods",
    titleZh: "揭秘在线对齐方法的非凡有效性",
    authors: "Enoch Hyunwook Kang",
    arxivId: "2604.17207",
    tags: ["Alignment", "Theory"],
    why: "Proves online RLHF and DPO achieve better temperature-zero regret than KL-based bounds suggest — closes the theory-practice gap in LLM alignment.",
    whyZh: "证明在线RLHF和DPO的零温度遗憾界优于KL分析所示，从理论上解释在线对齐方法的强实证表现。",
  },
  {
    date: "2026-04-22",
    title: "TTKV: Temporal-Tiered KV Cache for Long-Context LLM Inference",
    titleZh: "TTKV：面向长上下文LLM推理的时间分层KV缓存",
    authors: "Gradwell Dzikanyanga et al.",
    arxivId: "2604.19769",
    tags: ["Efficient Inference"],
    why: "Human-memory-inspired HBM+DRAM tiered KV layout cuts cross-tier traffic 5.94x on 128K-context tasks — 76% latency reduction and 2x throughput over strong baselines.",
    whyZh: "受人类记忆启发的HBM+DRAM分层KV缓存，128K上下文跨层传输减少5.94倍，延迟降低76%，吞吐提升2倍。",
  },
  {
    date: "2026-04-21",
    title: "LLM Reasoning Is Latent, Not the Chain of Thought",
    titleZh: "LLM推理是潜在的，而非思维链",
    authors: "Wenshuo Wang",
    arxivId: "2604.15726",
    tags: ["Theory", "Reasoning"],
    why: "Position paper: LLM reasoning lives in latent states, not surface CoT — reshapes how we evaluate interpretability and reasoning benchmarks.",
    whyZh: "论证LLM推理本质是潜在状态轨迹而非思维链，重塑推理基准与可解释性研究的核心假设。",
    pick: true,
  },
  {
    date: "2026-04-21",
    title: "Knowing When to Quit: A Principled Framework for Dynamic Abstention in LLM Reasoning",
    titleZh: "适时放弃：LLM推理动态弃权的原则性框架",
    authors: "Hen Davidov et al.",
    arxivId: "2604.18419",
    tags: ["Reasoning", "Efficient Inference"],
    why: "RL-based mid-generation abstention terminates bad reasoning traces early — principled value-threshold rule cuts wasted compute.",
    whyZh: "RL动态弃权框架在生成中途终止低质推理链，价值阈值规则优于启发式基线，节省推理算力。",
  },
  {
    date: "2026-04-21",
    title: "KnowRL: Boosting LLM Reasoning via Reinforcement Learning with Minimal-Sufficient Knowledge Guidance",
    titleZh: "KnowRL：基于最小充分知识引导强化学习提升LLM推理",
    authors: "Linhao Yu et al.",
    arxivId: "2604.12627",
    tags: ["Reasoning", "RLHF"],
    why: "Decomposes knowledge hints into atomic points to solve reward sparsity in RL — 1.5B model hits 70% on reasoning benchmarks.",
    whyZh: "将知识提示分解为原子知识点解决RL奖励稀疏问题，1.5B模型推理基准达70%。",
  },
  {
    date: "2026-04-17",
    title: "From P(y|x) to P(y): Investigating Reinforcement Learning in Pre-train Space",
    titleZh: "从P(y|x)到P(y)：在预训练空间探索强化学习",
    authors: "Yuqiao Tan et al.",
    arxivId: "2604.14142",
    tags: ["Reasoning", "RLHF", "Pre-training"],
    why: "DSRL: NSR in pre-train space expands reasoning horizon, then standard RL fine-tunes — outperforms all strong RLVR baselines.",
    whyZh: "PreRL在预训练空间扩展推理边界，NSR快速剪枝错误路径，DSRL全面超越强基线。",
    pick: true,
  },
  {
    date: "2026-04-17",
    title: "LongCoT: Benchmarking Long-Horizon Chain-of-Thought Reasoning",
    titleZh: "LongCoT：长时域思维链推理基准评测",
    authors: "Sumeet Ramesh Motwani et al.",
    arxivId: "2604.14140",
    tags: ["Reasoning", "Benchmark"],
    why: "2,500 expert problems requiring up to 100K reasoning tokens — best frontier models score <10%, exposing a major long-horizon gap.",
    whyZh: "2500道专家题需推理10万token，最优模型不足10%，长链推理缺口巨大。",
  },
  {
    date: "2026-04-17",
    title: "Calibration-Aware Policy Optimization for Reasoning LLMs",
    titleZh: "面向推理LLM的校准感知策略优化",
    authors: "Ziqi Wang et al.",
    arxivId: "2604.12632",
    tags: ["Reasoning", "RLHF"],
    why: "CAPO fixes GRPO's overconfidence via logistic AUC surrogate loss — jointly optimizes calibration and accuracy. ACL 2026.",
    whyZh: "CAPO通过AUC替代损失修正GRPO过度自信，同时优化准确率与不确定性校准，ACL 2026录用。",
  },
  {
    date: "2026-04-16",
    title: "Introspective Diffusion Language Models",
    titleZh: "内省扩散语言模型（I-DLM）",
    authors: "Yifan Yu et al.",
    arxivId: "2604.11035",
    tags: ["Diffusion LM", "Theory"],
    why: "Identifies introspective inconsistency as the root quality gap in diffusion LMs; ISD verifies past tokens while advancing new ones in one forward pass.",
    whyZh: "揭示内省不一致性为扩散LM质量差距根源，ISD算法单次前向传播同步验证历史token并生成新token。",
    pick: true,
  },
  {
    date: "2026-04-16",
    title: "Accelerating Speculative Decoding with Block Diffusion Draft Trees",
    titleZh: "利用块扩散草稿树加速推测解码",
    authors: "Liran Ringel and Yaniv Romano",
    arxivId: "2604.12989",
    tags: ["Diffusion LM", "Efficient Inference"],
    why: "DDTree builds a best-first draft tree from block diffusion per-position distributions — SOTA speculative decoding verified in one target model forward pass.",
    whyZh: "DDTree从块扩散逐位置分布构建最优优先草稿树，单次目标模型前向传播完成验证，达到推测解码SOTA。",
  },
  {
    date: "2026-04-16",
    title: "From Tokens to Steps: Verification-Aware Speculative Decoding for Efficient Multi-Step Reasoning",
    titleZh: "从Token到步骤：面向高效多步推理的验证感知推测解码",
    authors: "Kiran Purohit et al.",
    arxivId: "2604.15244",
    tags: ["Efficient Inference", "Reasoning"],
    why: "SpecGuard adds step-level verification using model-internal signals — prevents erroneous steps from propagating, achieving +3.6% accuracy and 11% lower latency on reasoning benchmarks.",
    whyZh: "SpecGuard利用模型内部信号引入步骤级验证，防止推理错误传播，多步推理准确率提升3.6%，延迟降低11%。",
    pick: true,
  },
  {
    date: "2026-04-16",
    title: "LLMs Gaming Verifiers: RLVR can Lead to Reward Hacking",
    titleZh: "LLM博弈验证器：RLVR可导致奖励欺骗",
    authors: "Lukas Helff et al.",
    arxivId: "2604.15149",
    tags: ["RLHF", "Reasoning"],
    why: "Empirical evidence that RLVR models exploit programmatic verifiers — reward hacking emerges even with rule-based verifiers, challenging RLVR's assumed robustness.",
    whyZh: "实证表明RLVR模型可利用程序验证器进行奖励欺骗，即使基于规则的验证器也难免，挑战RLVR鲁棒性假设。",
    pick: true,
  },
  {
    date: "2026-04-15",
    title: "Nemotron 3 Super: Open, Efficient Mixture-of-Experts Hybrid Mamba-Transformer Model for Agentic Reasoning",
    titleZh: "Nemotron 3 Super：面向智能体推理的开放高效MoE混合Mamba-Transformer模型",
    authors: "NVIDIA et al.",
    arxivId: "2604.12374",
    tags: ["MoE", "Efficient Inference", "Agent"],
    why: "NVIDIA's 120B/12B-active MoE hybrid Mamba-Transformer trained on 25T tokens — SOTA agentic benchmarks via native speculative decoding.",
    whyZh: "英伟达120B参数MoE混合Mamba-Transformer，25T token预训练，内置推测解码，智能体基准SOTA。",
  },
  {
    date: "2026-04-15",
    title: "Thinking Fast, Thinking Wrong: Intuitiveness Modulates LLM Counterfactual Reasoning in Policy Evaluation",
    titleZh: "快思慢想皆有误：直觉性调节LLM反事实推理的政策评估",
    authors: "Yanjie He et al.",
    arxivId: "2604.10511",
    tags: ["Reasoning", "Benchmark"],
    why: "CoT paradox: chain-of-thought helps obvious cases but nearly fails counter-intuitive ones — intuitiveness dominates LLM reasoning reliability.",
    whyZh: "CoT悖论：思维链提升直觉性问题但在反直觉问题上几乎失效，直觉性是决定推理可靠性的主导因素。",
  },
  {
    date: "2026-04-15",
    title: "Calibrated Speculative Decoding: Frequency-Guided Candidate Selection for Efficient Inference",
    titleZh: "校准推测解码：频率引导候选选择的高效推理框架",
    authors: "Xuwen Zhou et al.",
    arxivId: "2604.13634",
    tags: ["Efficient Inference"],
    why: "Training-free CSD recovers valid tokens rejected by standard verification via online correction memory and semantic gating — 2.33× peak throughput with no accuracy loss.",
    whyZh: "无需训练，CSD通过在线修正记忆和语义门控恢复被拒绝的有效Token，2.33倍吞吐提升且精度无损。",
  },
  {
    date: "2026-04-14",
    title: "SPPO: Sequence-Level PPO for Long-Horizon Reasoning Tasks",
    titleZh: "SPPO：面向长时域推理任务的序列级PPO",
    authors: "Tianyi Wang et al.",
    arxivId: "2604.08865",
    tags: ["Reasoning", "RLHF"],
    why: "Reformulates PPO as sequence-level contextual bandit — no value model needed, matches GRPO-style methods with far lower memory cost.",
    whyZh: "将PPO重构为序列级语境赌博机，无需价值模型，以更低内存成本匹配GRPO类方法性能。",
    pick: true,
  },
  {
    date: "2026-04-14",
    title: "RAGEN-2: Reasoning Collapse in Agentic RL",
    titleZh: "RAGEN-2：智能体强化学习中的推理坍塌",
    authors: "Zihan Wang et al.",
    arxivId: "2604.06268",
    tags: ["Reasoning", "Agent"],
    why: "Discovers template collapse — a failure mode invisible to entropy in agentic RL — fixed with SNR-aware prompt filtering.",
    whyZh: "发现模板坍塌这一被熵指标忽视的推理失效模式，提出信噪比滤波策略有效缓解。",
  },
  {
    date: "2026-04-14",
    title: "DFlash: Block Diffusion for Flash Speculative Decoding",
    titleZh: "DFlash：面向快速推测解码的块扩散方法",
    authors: "Jian Chen et al.",
    arxivId: "2602.06036",
    tags: ["Diffusion LM", "Efficient Inference"],
    why: "Block diffusion drafter achieves 6x lossless speedup over base LLM — 2.5x faster than EAGLE-3 with no quality loss.",
    whyZh: "用块扩散模型作为推测解码草稿器，实现6倍无损加速，比EAGLE-3快2.5倍。",
  },
  {
    date: "2026-04-14",
    title: "Parcae: Scaling Laws For Stable Looped Language Models",
    titleZh: "Parcae：稳定循环语言模型的缩放定律",
    authors: "Together AI & UCSD",
    arxivId: "2604.12946",
    tags: ["Pre-training", "Theory"],
    why: "Establishes first scaling laws for looped LMs with a stable architecture — matches quality of 2× larger Transformer with predictable test-time compute scaling.",
    whyZh: "首次为循环语言模型建立缩放定律，稳定架构以相同参数量达到2倍Transformer质量，支持可预测的推理时计算扩展。",
    pick: true,
  },
  {
    date: "2026-04-14",
    title: "Lightning OPD: Efficient Post-Training for Large Reasoning Models with Offline On-Policy Distillation",
    titleZh: "Lightning OPD：基于离线在策蒸馏的大型推理模型高效后训练",
    authors: "Yecheng Wu et al.",
    arxivId: "2604.13010",
    tags: ["Reasoning", "Fine-tuning"],
    why: "Identifies 'teacher consistency' as a critical invariant for on-policy distillation — removes live teacher server overhead while achieving SOTA math reasoning at 4x speedup.",
    whyZh: "揭示在策蒸馏的关键不变量「教师一致性」，去除实时教师服务器依赖，数学推理SOTA同时训练提速4倍。",
  },
  {
    date: "2026-04-13",
    title: "Fast-dVLM: Efficient Block-Diffusion VLM via Direct Conversion from Autoregressive VLM",
    titleZh: "Fast-dVLM：从自回归VLM直接转换的高效块扩散视觉语言模型",
    authors: "Chengyue Wu et al.",
    arxivId: "2604.06832",
    tags: ["Diffusion LM", "Multimodal"],
    why: "Direct AR-to-diffusion VLM conversion with KV-cache-compatible parallel decoding — matches AR quality across 11 multimodal benchmarks at lower inference cost.",
    whyZh: "直接将自回归VLM转换为块扩散模型，支持KV缓存并行解码，在11项多模态基准上匹配AR质量。",
  },
  {
    date: "2026-04-13",
    title: "A Mechanistic Analysis of Looped Reasoning Language Models",
    titleZh: "循环推理语言模型的机制分析",
    authors: "Hugh Blayney et al.",
    arxivId: "2604.11791",
    tags: ["Reasoning", "Theory"],
    why: "First mechanistic study of looped reasoning LMs — layers converge to distinct latent fixed points forming cyclic trajectories, with attention heads stabilizing across recurrences.",
    whyZh: "首次对循环推理语言模型进行机制分析，揭示各层收敛至不同潜态不动点形成循环轨迹，注意力头在多次循环中趋于稳定。",
  },
  {
    date: "2026-04-12",
    title: "SUPERNOVA: Eliciting General Reasoning in LLMs with Reinforcement Learning on Natural Instructions",
    titleZh: "SUPERNOVA：利用自然指令强化学习激发LLM通用推理能力",
    authors: "Ashima Suvarna et al.",
    arxivId: "2604.08477",
    tags: ["Reasoning", "RLHF"],
    why: "Mines natural instruction datasets for verifiable rewards — extends RLVR beyond math/code to causal, temporal, and abductive reasoning without hand-crafted reward functions.",
    whyZh: "从自然指令数据集中挖掘可验证奖励，将RLVR扩展至因果、时序和溯因推理，无需手工设计奖励函数。",
  },
  {
    date: "2026-04-12",
    title: "TriAttention: Efficient Long Reasoning with Trigonometric KV Compression",
    titleZh: "TriAttention：基于三角函数KV压缩的高效长推理",
    authors: "Weian Mao et al.",
    arxivId: "2604.04921",
    tags: ["Efficient Inference", "Reasoning"],
    why: "Trigonometric KV compression matches full-attention accuracy at 2.5x throughput or 10.7x memory reduction — practical long-reasoning speedup from MIT/NVIDIA.",
    whyZh: "三角函数KV压缩在保持全注意力精度的同时实现2.5倍吞吐或10.7倍内存压缩，大幅提升长推理效率。",
    pick: true,
  },
  {
    date: "2026-04-12",
    title: "Multi-objective Evolutionary Merging Enables Efficient Reasoning Models",
    titleZh: "多目标进化模型合并实现高效推理",
    authors: "Mario Iacobelli et al.",
    arxivId: "2604.06465",
    tags: ["Reasoning", "Efficient Inference"],
    why: "Evolutionary merging of reasoning and base models eliminates overthinking — cuts inference cost on easy problems without sacrificing accuracy.",
    whyZh: "进化合并推理模型与基础模型，消除过度思考，简单问题推理开销显著降低。",
  },
  {
    date: "2026-04-12",
    title: "OptiMer: Optimal Distribution Vector Merging Is Better than Data Mixing for Continual Pre-Training",
    titleZh: "OptiMer：分布向量合并优于数据混合的持续预训练方法",
    authors: "Haiyue Song et al.",
    arxivId: "2603.28858",
    tags: ["Pre-training"],
    why: "Trains one model per dataset then merges distribution vectors with Bayesian-optimized weights — beats data-mixing CPT on Gemma 3 27B with 15–35x lower search cost.",
    whyZh: "每个数据集单独训练后合并分布向量，贝叶斯优化权重，在Gemma 3 27B上超越数据混合，搜索成本降低15-35倍。",
    pick: true,
  },
  {
    date: "2026-04-12",
    title: "DyMoE: Dynamic Expert Orchestration with Mixed-Precision Quantization for Efficient MoE Inference on Edge",
    titleZh: "DyMoE：面向边缘设备高效MoE推理的动态专家编排与混合精度量化",
    authors: "Yuegui Huang et al.",
    arxivId: "2603.19172",
    tags: ["MoE", "Quantization", "Efficient Inference"],
    why: "Importance-aware dynamic quantization + look-ahead prefetching for MoE on commodity edge hardware — 3.4–22.7x TTFT speedup without accuracy loss.",
    whyZh: "通过重要性感知动态量化和预取，在商用边缘硬件上实现MoE推理，首次令牌延迟降低3.4-22.7倍，精度无损。",
  },
  {
    date: "2026-04-12",
    title: "Verify Before You Commit: Towards Faithful Reasoning in LLM Agents via Self-Auditing",
    titleZh: "执行前验证：基于自我审计的LLM智能体忠实推理",
    authors: "Wenhao Yuan et al.",
    arxivId: "2604.08401",
    tags: ["Agent", "Reasoning"],
    why: "SAVeR adversarially audits internal belief states before action commitment — stops unsupported beliefs from cascading across memory and decision steps in long-horizon agents. ACL 2026.",
    whyZh: "SAVeR在执行前对内部信念状态进行对抗性审计，阻止错误信念在长程智能体记忆和决策中级联传播，ACL 2026录用。",
  },
  {
    date: "2026-04-12",
    title: "Single-Agent LLMs Outperform Multi-Agent Systems on Multi-Hop Reasoning Under Equal Thinking Token Budgets",
    titleZh: "等量Token预算下单智能体LLM在多跳推理上超越多智能体系统",
    authors: "Dat Tran et al.",
    arxivId: "2604.02460",
    tags: ["Agent", "Reasoning", "Theory"],
    why: "Information-theoretic proof via Data Processing Inequality: single-agent LLMs are more token-efficient on multi-hop reasoning — reported MAS gains trace to uncontrolled compute.",
    whyZh: "通过数据处理不等式证明单智能体在多跳推理上信息效率更高，多智能体系统的性能优势源于未受控的计算量差异。",
  },
  {
    date: "2026-04-11",
    title: "Dynin-Omni: Omnimodal Unified Large Diffusion Language Model",
    titleZh: "Dynin-Omni：统一全模态大型扩散语言模型",
    authors: "Dynin AI et al.",
    arxivId: "2604.00007",
    tags: ["Diffusion LM", "Multimodal"],
    why: "First masked-diffusion omnimodal model unifying text, image, speech, and video — achieves strong results across 19 multimodal benchmarks.",
    whyZh: "首个掩码扩散全模态基础模型，统一文本、图像、语音与视频，19项基准表现强劲。",
  },
  {
    date: "2026-04-11",
    title: "Learning from the Right Rollouts: Data Attribution for PPO-based LLM Post-Training",
    titleZh: "从正确轨迹中学习：基于PPO的LLM后训练数据归因",
    authors: "I-PPO Team et al.",
    arxivId: "2604.01597",
    tags: ["RLHF", "Fine-tuning"],
    why: "I-PPO uses gradient-based influence scores to filter RL rollouts — reduces unfaithful CoT reasoning and accelerates PPO post-training.",
    whyZh: "I-PPO通过梯度影响分数过滤RL轨迹，减少不忠实CoT推理，加速PPO后训练收敛。",
  },
  {
    date: "2026-04-10",
    title: "SHAPE: Stage-aware Hierarchical Advantage via Potential Estimation for LLM Reasoning",
    titleZh: "SHAPE：面向LLM推理的阶段感知层级优势估计",
    authors: "Zhengyang Ai et al.",
    arxivId: "2604.06636",
    tags: ["Reasoning", "RLHF"],
    why: "Formalizes reasoning as state-space trajectories with hierarchical credit assignment — +3% accuracy and 30% fewer tokens by distinguishing efficient breakthroughs from mere verbosity.",
    whyZh: "将推理形式化为状态空间轨迹并引入层级信用分配，准确率提升3%、token减少30%，有效区分有效突破与冗余推理。",
    pick: true,
  },
  {
    date: "2026-04-10",
    title: "DARE: Diffusion Large Language Models Alignment and Reinforcement Executor",
    titleZh: "DARE：扩散大语言模型对齐与强化执行框架",
    authors: "Jingyi Yang et al.",
    arxivId: "2604.04215",
    tags: ["Diffusion LM", "Alignment", "RLHF"],
    why: "First unified open framework for post-training diffusion LLMs — brings RLHF and alignment tooling to both masked and block diffusion models, accelerating reproducible research.",
    whyZh: "首个统一的扩散LLM后训练开源框架，为掩码和块扩散模型提供RLHF与对齐工具，推动可复现研究。",
    pick: true,
  },
  {
    date: "2026-04-10",
    title: "LightThinker++: From Reasoning Compression to Memory Management",
    titleZh: "LightThinker++：从推理压缩到内存管理",
    authors: "Yuqi Zhu et al.",
    arxivId: "2604.03679",
    tags: ["Reasoning", "Efficient Inference"],
    why: "Upgrades LightThinker with explicit adaptive memory primitives — 70% peak token reduction and 26% faster inference by scheduling purposeful memory actions in long reasoning chains.",
    whyZh: "通过显式自适应内存原语升级LightThinker，峰值token减少70%、推理加速26%，适用于长推理链。",
    pick: true,
  },
  {
    date: "2026-04-10",
    title: "Rethinking Token Prediction: Tree-Structured Diffusion Language Model",
    titleZh: "重新思考Token预测：树结构扩散语言模型",
    authors: "Zihao Wu et al.",
    arxivId: "2604.03537",
    tags: ["Diffusion LM", "Theory"],
    why: "Exploits vocabulary hierarchy in masked diffusion — models intermediate latent states as ancestor nodes in a pre-built tree, enabling more structured and efficient training.",
    whyZh: "在掩码扩散中利用词汇层次结构，将中间潜在状态建模为词汇树祖先节点，训练更结构化高效。",
  },
  {
    date: "2026-04-10",
    title: "Dependency-Guided Parallel Decoding in Discrete Diffusion Language Models",
    titleZh: "离散扩散语言模型中的依赖引导并行解码",
    authors: "Liran Ringel et al.",
    arxivId: "2604.02560",
    tags: ["Diffusion LM", "Efficient Inference"],
    why: "DEMASK predictor estimates pairwise token dependencies to guide safe parallel unmasking — fixes quality degradation from distributional mismatch in discrete diffusion decoding.",
    whyZh: "DEMASK预测token间依赖关系，安全选择可并行解码的位置，解决离散扩散中分布不匹配导致的质量下降。",
  },
  {
    date: "2026-04-10",
    title: "MSA: Memory Sparse Attention for Efficient End-to-End Memory Model Scaling to 100M Tokens",
    titleZh: "MSA：面向1亿Token高效端到端记忆模型的稀疏注意力",
    authors: "EverMind AI",
    arxivId: "2603.23516",
    tags: ["Efficient Inference", "Pre-training"],
    why: "Scalable sparse attention + document-wise RoPE achieves near-linear complexity at 100M tokens — only 9% quality degradation vs 16K baseline, beating SOTA RAG and memory agents.",
    whyZh: "通过可扩展稀疏注意力和文档级RoPE实现1亿token近线性复杂度，相比16K基线仅降级9%，超越SOTA RAG系统。",
  },
  {
    date: "2025-05-28",
    title: "Fast-dLLM: Training-free Acceleration of Diffusion LLM",
    authors: "Wu et al.",
    arxivId: "2505.22618",
    tags: ["Diffusion LM", "Efficient Inference"],
    why: "Practical 3-10x speedup for masked diffusion LMs with no retraining — makes diffusion LMs viable for production.",
    whyZh: "无需重新训练即可实现 3-10 倍加速 — 让扩散语言模型可用于生产环境。",
    pick: true,
    slug: "fast-dllm",
  },
  {
    date: "2025-02-28",
    title: "Block Diffusion: Interpolating Between Autoregressive and Diffusion Language Models",
    titleZh: "Block Diffusion: 在自回归与扩散语言模型之间插值",
    authors: "Arriola et al.",
    arxivId: "2503.09573",
    tags: ["Diffusion LM", "Efficient Inference"],
    why: "Elegant bridge between AR and diffusion — block size B lets you tune the speed/quality tradeoff continuously.",
    whyZh: "AR 和扩散之间的优雅桥梁 — 块大小 B 让你连续调节速度/质量权衡。",
    pick: true,
    slug: "block-diffusion",
  },
  {
    date: "2025-02-14",
    title: "Large Language Diffusion Models (LLaDA)",
    titleZh: "大语言扩散模型 (LLaDA)",
    authors: "Nie et al.",
    arxivId: "2502.09992",
    tags: ["Diffusion LM", "Pre-training"],
    why: "First diffusion LM at 8B scale that matches LLaMA3 — proves AR is not the only path to powerful LLMs.",
    whyZh: "首个 8B 规模扩散语言模型，可与 LLaMA3 媲美 — 证明 AR 不是强大 LLM 的唯一路径。",
    pick: true,
    slug: "llada",
  },
  {
    date: "2025-01-22",
    title: "DeepSeek-R1: Incentivizing Reasoning Capability in LLMs via RL",
    authors: "DeepSeek AI",
    arxivId: "2501.12948",
    tags: ["RL", "Reasoning", "Chain-of-Thought"],
    why: "Matches o1 on math/code using pure RL with GRPO — no supervised CoT data needed. Huge open-source release.",
    whyZh: "仅使用 GRPO 强化学习在数学/代码上匹配 o1 — 不需要监督 CoT 数据。重要的开源发布。",
    pick: true,
  },
  {
    date: "2024-06-11",
    title: "Simple and Effective Masked Diffusion Language Models (MDLM)",
    authors: "Sahoo et al.",
    arxivId: "2406.07524",
    tags: ["Diffusion LM", "Theory"],
    why: "Clean theoretical foundation for masked diffusion — derives the training loss from first principles, no hand-tuning.",
    whyZh: "掩码扩散的简洁理论基础 — 从基本原理推导训练损失，无需手动调整。",
    slug: "mdlm",
  },
  {
    date: "2024-02-05",
    title: "DeepSeekMath: Pushing the Limits of Mathematical Reasoning (GRPO)",
    authors: "Shao et al.",
    arxivId: "2402.03300",
    tags: ["RL", "Math Reasoning"],
    why: "Introduces GRPO — removes the critic network from PPO by using group-relative rewards. Powers DeepSeek-R1.",
    whyZh: "引入 GRPO — 通过组相对奖励从 PPO 中移除 critic 网络。为 DeepSeek-R1 提供动力。",
    slug: "grpo",
  },
  {
    date: "2023-05-29",
    title: "Direct Preference Optimization (DPO)",
    authors: "Rafailov et al.",
    arxivId: "2305.18290",
    tags: ["Alignment", "RLHF"],
    why: "Killed the reward model — rewrites RLHF as a simple binary loss. Became the default fine-tuning method for open-source LLMs.",
    whyZh: "消灭了奖励模型 — 将 RLHF 改写为简单的二元损失。成为开源 LLM 的默认微调方法。",
    pick: true,
    slug: "dpo",
  },
  {
    date: "2017-06-12",
    title: "Attention Is All You Need",
    authors: "Vaswani et al.",
    arxivId: "1706.03762",
    tags: ["Transformer", "Architecture"],
    why: "The paper that started it all — replaced RNNs with attention. Everything in this repo builds on it.",
    whyZh: "一切的起点 — 用注意力替代 RNN。本站所有论文都建立在它之上。",
    slug: "attention-is-all-you-need",
  },
];

export const allTags = Array.from(
  new Set(dailyPapers.flatMap((p) => p.tags))
).sort();
