"use client";

import { useLang } from "@/lib/i18n";
import { LlmGuideChapterBar } from "@/components/LlmGuideChapterBar";
import { LlmGuideNav } from "@/components/LlmGuideNav";
import { LlmGuideToc } from "@/components/LlmGuideToc";

export default function Page() {
  const { t } = useLang();
  const html = `<h3 id="1-motivation-cbdpgdzdyh-jyybzdrrxxhl"><strong>1. Motivation: 从被动评估到主动优化, 将语义保真度融入学习环路</strong></h3>
<h4 id="1-1-ai-xtsjdhxtz"><strong>1.1 AI 系统设计的核心挑战</strong></h4>
<p>在人工智能 (AI) 系统, 特别是那些作为复杂管道一部分的系统 (如文档理解) 中, 一个核心挑战是<strong>端到端性能的优化</strong>. 当前 OCR 系统的开发流程存在一个断裂: 模型在训练时优化一个代理损失 (如 CTC Loss), 而在评估时却使用一个与下游任务语义关联较弱的指标 (如 CA). 这导致了所谓的“<strong>代理鸿沟</strong>” (surrogate gap): 模型在代理指标上表现优异, 但其输出的表征却可能严重损害下游任务的性能.</p>
<p>我们的工作从一个 AI 系统设计的视角出发: 能否设计一个评估指标, 它不仅能更真实地反映语义保真度, 而且能够<strong>被整合进训练过程</strong>, 成为一个可优化的目标? 换言之, 我们寻求将评估指标从一个<strong>被动的裁判</strong>, 转变为一个<strong>主动的教练</strong>.</p>
<h4 id="1-2-kw-srd-gjkxxdyyqz"><strong>1.2 可微 SRD: 构建可学习的语义权重</strong></h4>
<p>传统的 SRD (Semantic Restoration Degree) 定义依赖于一个预设的重要性评分 <span class="katex"><span class="katex-mathml"><math xmlns="http://www.w3.org/1998/Math/MathML"><semantics><mrow><msub><mi>I</mi><mi>i</mi></msub></mrow><annotation encoding="application/x-tex">I_i</annotation></semantics></math></span><span class="katex-html" aria-hidden="true"><span class="base"><span class="strut" style="height:0.8333em;vertical-align:-0.15em;"></span><span class="mord"><span class="mord mathnormal" style="margin-right:0.0785em;">I</span><span class="msupsub"><span class="vlist-t vlist-t2"><span class="vlist-r"><span class="vlist" style="height:0.3117em;"><span style="top:-2.55em;margin-left:-0.0785em;margin-right:0.05em;"><span class="pstrut" style="height:2.7em;"></span><span class="sizing reset-size6 size3 mtight"><span class="mord mathnormal mtight">i</span></span></span></span><span class="vlist-s">​</span></span><span class="vlist-r"><span class="vlist" style="height:0.15em;"><span></span></span></span></span></span></span></span></span></span>, 这使其难以在基于梯度的优化中直接使用. 为了解决这个问题, 我们提出了一个<strong>可微的 SRD 代理</strong> (differentiable SRD surrogate). 核心思想是引入一个轻量级的权重预测网络 <span class="katex"><span class="katex-mathml"><math xmlns="http://www.w3.org/1998/Math/MathML"><semantics><mrow><msub><mi>h</mi><mi>θ</mi></msub><mo stretchy="false">(</mo><mo>⋅</mo><mo stretchy="false">)</mo></mrow><annotation encoding="application/x-tex">h_{\\theta}(\\cdot)</annotation></semantics></math></span><span class="katex-html" aria-hidden="true"><span class="base"><span class="strut" style="height:1em;vertical-align:-0.25em;"></span><span class="mord"><span class="mord mathnormal">h</span><span class="msupsub"><span class="vlist-t vlist-t2"><span class="vlist-r"><span class="vlist" style="height:0.3361em;"><span style="top:-2.55em;margin-left:0em;margin-right:0.05em;"><span class="pstrut" style="height:2.7em;"></span><span class="sizing reset-size6 size3 mtight"><span class="mord mtight"><span class="mord mathnormal mtight" style="margin-right:0.0278em;">θ</span></span></span></span></span><span class="vlist-s">​</span></span><span class="vlist-r"><span class="vlist" style="height:0.15em;"><span></span></span></span></span></span></span><span class="mopen">(</span><span class="mord">⋅</span><span class="mclose">)</span></span></span></span>, 该网络与主干 OCR 模型一同训练.</p>
<p>给定 OCR 模型产生的中间特征 <span class="katex"><span class="katex-mathml"><math xmlns="http://www.w3.org/1998/Math/MathML"><semantics><mrow><mi>F</mi></mrow><annotation encoding="application/x-tex">F</annotation></semantics></math></span><span class="katex-html" aria-hidden="true"><span class="base"><span class="strut" style="height:0.6833em;"></span><span class="mord mathnormal" style="margin-right:0.1389em;">F</span></span></span></span>, 权重预测器 <span class="katex"><span class="katex-mathml"><math xmlns="http://www.w3.org/1998/Math/MathML"><semantics><mrow><msub><mi>h</mi><mi>θ</mi></msub></mrow><annotation encoding="application/x-tex">h_{\\theta}</annotation></semantics></math></span><span class="katex-html" aria-hidden="true"><span class="base"><span class="strut" style="height:0.8444em;vertical-align:-0.15em;"></span><span class="mord"><span class="mord mathnormal">h</span><span class="msupsub"><span class="vlist-t vlist-t2"><span class="vlist-r"><span class="vlist" style="height:0.3361em;"><span style="top:-2.55em;margin-left:0em;margin-right:0.05em;"><span class="pstrut" style="height:2.7em;"></span><span class="sizing reset-size6 size3 mtight"><span class="mord mtight"><span class="mord mathnormal mtight" style="margin-right:0.0278em;">θ</span></span></span></span></span><span class="vlist-s">​</span></span><span class="vlist-r"><span class="vlist" style="height:0.15em;"><span></span></span></span></span></span></span></span></span></span> 为每个字符或词元 <span class="katex"><span class="katex-mathml"><math xmlns="http://www.w3.org/1998/Math/MathML"><semantics><mrow><msub><mi>s</mi><mi>i</mi></msub></mrow><annotation encoding="application/x-tex">s_i</annotation></semantics></math></span><span class="katex-html" aria-hidden="true"><span class="base"><span class="strut" style="height:0.5806em;vertical-align:-0.15em;"></span><span class="mord"><span class="mord mathnormal">s</span><span class="msupsub"><span class="vlist-t vlist-t2"><span class="vlist-r"><span class="vlist" style="height:0.3117em;"><span style="top:-2.55em;margin-left:0em;margin-right:0.05em;"><span class="pstrut" style="height:2.7em;"></span><span class="sizing reset-size6 size3 mtight"><span class="mord mathnormal mtight">i</span></span></span></span><span class="vlist-s">​</span></span><span class="vlist-r"><span class="vlist" style="height:0.15em;"><span></span></span></span></span></span></span></span></span></span> 输出其重要性评分:</p>
<p>\$I_i = h_{\\theta}(F, i)
\\quad(1)\$</p>
<p>通过这种方式, 整个 SRD 的计算过程对于参数 <span class="katex"><span class="katex-mathml"><math xmlns="http://www.w3.org/1998/Math/MathML"><semantics><mrow><mi>θ</mi></mrow><annotation encoding="application/x-tex">\\theta</annotation></semantics></math></span><span class="katex-html" aria-hidden="true"><span class="base"><span class="strut" style="height:0.6944em;"></span><span class="mord mathnormal" style="margin-right:0.0278em;">θ</span></span></span></span> 变得完全可微. 这使得我们能将 SRD 直接作为训练目标的一部分.</p>
<h4 id="1-3-mxxyrwdlhxlkj"><strong>1.3 面向下游任务的联合训练框架</strong></h4>
<p>我们将可微 SRD 整合到一个联合训练框架中. 总的损失函数 <span class="katex"><span class="katex-mathml"><math xmlns="http://www.w3.org/1998/Math/MathML"><semantics><mrow><msub><mi mathvariant="script">L</mi><mrow><mi>t</mi><mi>o</mi><mi>t</mi><mi>a</mi><mi>l</mi></mrow></msub></mrow><annotation encoding="application/x-tex">\\mathcal{L}_{total}</annotation></semantics></math></span><span class="katex-html" aria-hidden="true"><span class="base"><span class="strut" style="height:0.8333em;vertical-align:-0.15em;"></span><span class="mord"><span class="mord mathcal">L</span><span class="msupsub"><span class="vlist-t vlist-t2"><span class="vlist-r"><span class="vlist" style="height:0.3361em;"><span style="top:-2.55em;margin-left:0em;margin-right:0.05em;"><span class="pstrut" style="height:2.7em;"></span><span class="sizing reset-size6 size3 mtight"><span class="mord mtight"><span class="mord mathnormal mtight">t</span><span class="mord mathnormal mtight">o</span><span class="mord mathnormal mtight">t</span><span class="mord mathnormal mtight">a</span><span class="mord mathnormal mtight" style="margin-right:0.0197em;">l</span></span></span></span></span><span class="vlist-s">​</span></span><span class="vlist-r"><span class="vlist" style="height:0.15em;"><span></span></span></span></span></span></span></span></span></span> 由传统的 OCR 损失 (如 CTC Loss) 和最大化 SRD 的损失项组成:</p>
<p>\$\\mathcal{L}<em>{total} = \\mathcal{L}</em>{OCR} - \\lambda \\cdot \\mathbb{E}<em>{(S,G) \\sim \\mathcal{D}} \\left[ \\text{SRD}(S, G; h</em>{\\theta}) \\right]
\\quad(2)\$</p>
<p>其中, <span class="katex"><span class="katex-mathml"><math xmlns="http://www.w3.org/1998/Math/MathML"><semantics><mrow><mi>λ</mi></mrow><annotation encoding="application/x-tex">\\lambda</annotation></semantics></math></span><span class="katex-html" aria-hidden="true"><span class="base"><span class="strut" style="height:0.6944em;"></span><span class="mord mathnormal">λ</span></span></span></span> 是一个超参数, 用于平衡字符级准确性和语义级保真度. 负号表示我们希望<strong>最大化</strong> SRD. 通过最小化这个复合损失, OCR 模型不仅学习如何正确识别字符, 而且 <span class="katex"><span class="katex-mathml"><math xmlns="http://www.w3.org/1998/Math/MathML"><semantics><mrow><msub><mi>h</mi><mi>θ</mi></msub></mrow><annotation encoding="application/x-tex">h_{\\theta}</annotation></semantics></math></span><span class="katex-html" aria-hidden="true"><span class="base"><span class="strut" style="height:0.8444em;vertical-align:-0.15em;"></span><span class="mord"><span class="mord mathnormal">h</span><span class="msupsub"><span class="vlist-t vlist-t2"><span class="vlist-r"><span class="vlist" style="height:0.3361em;"><span style="top:-2.55em;margin-left:0em;margin-right:0.05em;"><span class="pstrut" style="height:2.7em;"></span><span class="sizing reset-size6 size3 mtight"><span class="mord mtight"><span class="mord mathnormal mtight" style="margin-right:0.0278em;">θ</span></span></span></span></span><span class="vlist-s">​</span></span><span class="vlist-r"><span class="vlist" style="height:0.15em;"><span></span></span></span></span></span></span></span></span></span> 也学会了如何根据上下文<strong>动态地识别出对整体语义最重要的部分</strong>. 这是一种任务驱动的内部注意力机制, 它使模型天生就具备了保护关键语义信息的能力.</p>
<h4 id="1-4-conclusion"><strong>1.4 Conclusion</strong></h4>
<p>在 AAAI 的视角下, 我们将 SRD 从一个静态的评估指标, 升级为了一个动态的、可学习的系统组件. 通过设计可微的权重预测器并将其融入端到端的训练框架, 我们不仅弥合了训练与评估之间的“代理鸿沟”, 更重要的是, 我们创造出了一种能够<strong>自我感知语义重要性</strong>的智能 OCR 系统. 这种方法论为构建与下游任务更协调、更鲁棒的 AI 系统提供了新的思路.</p>
<hr>
<h4 id="english-version"><strong>English Version</strong></h4>
<h3 id="1-motivation-from-passive-evaluation-to-active-optimization-integrating-semantic-fidelity-into-the-learning-loop"><strong>1. Motivation: From Passive Evaluation to Active Optimization: Integrating Semantic Fidelity into the Learning Loop</strong></h3>
<h4 id="1-1-the-core-challenge-in-ai-system-design"><strong>1.1 The Core Challenge in AI System Design</strong></h4>
<p>A core challenge in Artificial Intelligence (AI) systems, especially those part of a complex pipeline (e.g., document understanding), is the optimization of <strong>end-to-end performance</strong>. The development workflow for current OCR systems suffers from a disconnection: models are trained to optimize a surrogate loss (e.g., CTC Loss) but are evaluated using a metric (e.g., CA) that correlates poorly with the semantics required by downstream tasks. This creates a &quot;<strong>surrogate gap</strong>&quot;: a model may excel on the surrogate metric, yet its output representation can severely damage the performance of subsequent tasks.</p>
<p>Our work originates from an AI system design perspective: can we design an evaluation metric that not only reflects semantic fidelity more genuinely but can also be <strong>integrated into the training process</strong> as an optimizable objective? In other words, we seek to transform the metric from a <strong>passive judge</strong> into an <strong>active coach</strong>.</p>
<h4 id="1-2-differentiable-srd-building-a-learnable-semantic-weighter"><strong>1.2 Differentiable SRD: Building a Learnable Semantic Weighter</strong></h4>
<p>The traditional definition of SRD (Semantic Restoration Degree) relies on a predefined importance score <span class="katex"><span class="katex-mathml"><math xmlns="http://www.w3.org/1998/Math/MathML"><semantics><mrow><msub><mi>I</mi><mi>i</mi></msub></mrow><annotation encoding="application/x-tex">I_i</annotation></semantics></math></span><span class="katex-html" aria-hidden="true"><span class="base"><span class="strut" style="height:0.8333em;vertical-align:-0.15em;"></span><span class="mord"><span class="mord mathnormal" style="margin-right:0.0785em;">I</span><span class="msupsub"><span class="vlist-t vlist-t2"><span class="vlist-r"><span class="vlist" style="height:0.3117em;"><span style="top:-2.55em;margin-left:-0.0785em;margin-right:0.05em;"><span class="pstrut" style="height:2.7em;"></span><span class="sizing reset-size6 size3 mtight"><span class="mord mathnormal mtight">i</span></span></span></span><span class="vlist-s">​</span></span><span class="vlist-r"><span class="vlist" style="height:0.15em;"><span></span></span></span></span></span></span></span></span></span>, making it difficult to use directly in gradient-based optimization. To address this, we propose a <strong>differentiable SRD surrogate</strong>. The core idea is to introduce a lightweight weight prediction network, <span class="katex"><span class="katex-mathml"><math xmlns="http://www.w3.org/1998/Math/MathML"><semantics><mrow><msub><mi>h</mi><mi>θ</mi></msub><mo stretchy="false">(</mo><mo>⋅</mo><mo stretchy="false">)</mo></mrow><annotation encoding="application/x-tex">h_{\\theta}(\\cdot)</annotation></semantics></math></span><span class="katex-html" aria-hidden="true"><span class="base"><span class="strut" style="height:1em;vertical-align:-0.25em;"></span><span class="mord"><span class="mord mathnormal">h</span><span class="msupsub"><span class="vlist-t vlist-t2"><span class="vlist-r"><span class="vlist" style="height:0.3361em;"><span style="top:-2.55em;margin-left:0em;margin-right:0.05em;"><span class="pstrut" style="height:2.7em;"></span><span class="sizing reset-size6 size3 mtight"><span class="mord mtight"><span class="mord mathnormal mtight" style="margin-right:0.0278em;">θ</span></span></span></span></span><span class="vlist-s">​</span></span><span class="vlist-r"><span class="vlist" style="height:0.15em;"><span></span></span></span></span></span></span><span class="mopen">(</span><span class="mord">⋅</span><span class="mclose">)</span></span></span></span>, which is trained jointly with the main OCR model.</p>
<p>Given the intermediate features <span class="katex"><span class="katex-mathml"><math xmlns="http://www.w3.org/1998/Math/MathML"><semantics><mrow><mi>F</mi></mrow><annotation encoding="application/x-tex">F</annotation></semantics></math></span><span class="katex-html" aria-hidden="true"><span class="base"><span class="strut" style="height:0.6833em;"></span><span class="mord mathnormal" style="margin-right:0.1389em;">F</span></span></span></span> from the OCR model, the weight predictor <span class="katex"><span class="katex-mathml"><math xmlns="http://www.w3.org/1998/Math/MathML"><semantics><mrow><msub><mi>h</mi><mi>θ</mi></msub></mrow><annotation encoding="application/x-tex">h_{\\theta}</annotation></semantics></math></span><span class="katex-html" aria-hidden="true"><span class="base"><span class="strut" style="height:0.8444em;vertical-align:-0.15em;"></span><span class="mord"><span class="mord mathnormal">h</span><span class="msupsub"><span class="vlist-t vlist-t2"><span class="vlist-r"><span class="vlist" style="height:0.3361em;"><span style="top:-2.55em;margin-left:0em;margin-right:0.05em;"><span class="pstrut" style="height:2.7em;"></span><span class="sizing reset-size6 size3 mtight"><span class="mord mtight"><span class="mord mathnormal mtight" style="margin-right:0.0278em;">θ</span></span></span></span></span><span class="vlist-s">​</span></span><span class="vlist-r"><span class="vlist" style="height:0.15em;"><span></span></span></span></span></span></span></span></span></span> outputs an importance score for each character or token <span class="katex"><span class="katex-mathml"><math xmlns="http://www.w3.org/1998/Math/MathML"><semantics><mrow><msub><mi>s</mi><mi>i</mi></msub></mrow><annotation encoding="application/x-tex">s_i</annotation></semantics></math></span><span class="katex-html" aria-hidden="true"><span class="base"><span class="strut" style="height:0.5806em;vertical-align:-0.15em;"></span><span class="mord"><span class="mord mathnormal">s</span><span class="msupsub"><span class="vlist-t vlist-t2"><span class="vlist-r"><span class="vlist" style="height:0.3117em;"><span style="top:-2.55em;margin-left:0em;margin-right:0.05em;"><span class="pstrut" style="height:2.7em;"></span><span class="sizing reset-size6 size3 mtight"><span class="mord mathnormal mtight">i</span></span></span></span><span class="vlist-s">​</span></span><span class="vlist-r"><span class="vlist" style="height:0.15em;"><span></span></span></span></span></span></span></span></span></span>:</p>
<p>\$I_i = h_{\\theta}(F, i)
\\quad(1)\$</p>
<p>By doing so, the entire SRD computation becomes fully differentiable with respect to the parameters <span class="katex"><span class="katex-mathml"><math xmlns="http://www.w3.org/1998/Math/MathML"><semantics><mrow><mi>θ</mi></mrow><annotation encoding="application/x-tex">\\theta</annotation></semantics></math></span><span class="katex-html" aria-hidden="true"><span class="base"><span class="strut" style="height:0.6944em;"></span><span class="mord mathnormal" style="margin-right:0.0278em;">θ</span></span></span></span>. This enables us to incorporate SRD directly into the training objective.</p>
<h4 id="1-3-a-joint-training-framework-for-downstream-awareness"><strong>1.3 A Joint Training Framework for Downstream Awareness</strong></h4>
<p>We integrate the differentiable SRD into a joint training framework. The total loss function, <span class="katex"><span class="katex-mathml"><math xmlns="http://www.w3.org/1998/Math/MathML"><semantics><mrow><msub><mi mathvariant="script">L</mi><mrow><mi>t</mi><mi>o</mi><mi>t</mi><mi>a</mi><mi>l</mi></mrow></msub></mrow><annotation encoding="application/x-tex">\\mathcal{L}_{total}</annotation></semantics></math></span><span class="katex-html" aria-hidden="true"><span class="base"><span class="strut" style="height:0.8333em;vertical-align:-0.15em;"></span><span class="mord"><span class="mord mathcal">L</span><span class="msupsub"><span class="vlist-t vlist-t2"><span class="vlist-r"><span class="vlist" style="height:0.3361em;"><span style="top:-2.55em;margin-left:0em;margin-right:0.05em;"><span class="pstrut" style="height:2.7em;"></span><span class="sizing reset-size6 size3 mtight"><span class="mord mtight"><span class="mord mathnormal mtight">t</span><span class="mord mathnormal mtight">o</span><span class="mord mathnormal mtight">t</span><span class="mord mathnormal mtight">a</span><span class="mord mathnormal mtight" style="margin-right:0.0197em;">l</span></span></span></span></span><span class="vlist-s">​</span></span><span class="vlist-r"><span class="vlist" style="height:0.15em;"><span></span></span></span></span></span></span></span></span></span>, is composed of a traditional OCR loss (e.g., CTC Loss) and a loss term for maximizing SRD:</p>
<p>\$\\mathcal{L}<em>{total} = \\mathcal{L}</em>{OCR} - \\lambda \\cdot \\mathbb{E}<em>{(S,G) \\sim \\mathcal{D}} \\left[ \\text{SRD}(S, G; h</em>{\\theta}) \\right]
\\quad(2)\$</p>
<p>Here, <span class="katex"><span class="katex-mathml"><math xmlns="http://www.w3.org/1998/Math/MathML"><semantics><mrow><mi>λ</mi></mrow><annotation encoding="application/x-tex">\\lambda</annotation></semantics></math></span><span class="katex-html" aria-hidden="true"><span class="base"><span class="strut" style="height:0.6944em;"></span><span class="mord mathnormal">λ</span></span></span></span> is a hyperparameter that balances character-level accuracy and semantic-level fidelity. The negative sign indicates our objective to <strong>maximize</strong> the SRD. By minimizing this composite loss, the OCR model not only learns to recognize characters correctly, but the weighter <span class="katex"><span class="katex-mathml"><math xmlns="http://www.w3.org/1998/Math/MathML"><semantics><mrow><msub><mi>h</mi><mi>θ</mi></msub></mrow><annotation encoding="application/x-tex">h_{\\theta}</annotation></semantics></math></span><span class="katex-html" aria-hidden="true"><span class="base"><span class="strut" style="height:0.8444em;vertical-align:-0.15em;"></span><span class="mord"><span class="mord mathnormal">h</span><span class="msupsub"><span class="vlist-t vlist-t2"><span class="vlist-r"><span class="vlist" style="height:0.3361em;"><span style="top:-2.55em;margin-left:0em;margin-right:0.05em;"><span class="pstrut" style="height:2.7em;"></span><span class="sizing reset-size6 size3 mtight"><span class="mord mtight"><span class="mord mathnormal mtight" style="margin-right:0.0278em;">θ</span></span></span></span></span><span class="vlist-s">​</span></span><span class="vlist-r"><span class="vlist" style="height:0.15em;"><span></span></span></span></span></span></span></span></span></span> also learns to <strong>dynamically identify which parts of the text are most crucial to the overall semantics</strong> based on context. This acts as a task-driven internal attention mechanism, endowing the model with an intrinsic ability to preserve critical semantic information.</p>
<h4 id="1-4-conclusion-2"><strong>1.4 Conclusion</strong></h4>
<p>From an AAAI perspective, we elevate SRD from a static evaluation metric to a dynamic, learnable component of the system. By designing a differentiable weight predictor and integrating it into an end-to-end training framework, we not only bridge the &quot;surrogate gap&quot; between training and evaluation but, more importantly, we create an intelligent OCR system that is <strong>self-aware of semantic importance</strong>. This methodology offers a new path toward building more robust AI systems that are better aligned with their downstream applications.</p>
`;
  const toc: { level: number; id: string; text: string }[] = [{"level":3,"id":"1-motivation-cbdpgdzdyh-jyybzdrrxxhl","text":"1. Motivation: 从被动评估到主动优化, 将语义保真度融入学习环路"},{"level":4,"id":"1-1-ai-xtsjdhxtz","text":"1.1 AI 系统设计的核心挑战"},{"level":4,"id":"1-2-kw-srd-gjkxxdyyqz","text":"1.2 可微 SRD: 构建可学习的语义权重"},{"level":4,"id":"1-3-mxxyrwdlhxlkj","text":"1.3 面向下游任务的联合训练框架"},{"level":4,"id":"1-4-conclusion","text":"1.4 Conclusion"},{"level":4,"id":"english-version","text":"English Version"},{"level":3,"id":"1-motivation-from-passive-evaluation-to-active-optimization-integrating-semantic-fidelity-into-the-learning-loop","text":"1. Motivation: From Passive Evaluation to Active Optimization: Integrating Semantic Fidelity into the Learning Loop"},{"level":4,"id":"1-1-the-core-challenge-in-ai-system-design","text":"1.1 The Core Challenge in AI System Design"},{"level":4,"id":"1-2-differentiable-srd-building-a-learnable-semantic-weighter","text":"1.2 Differentiable SRD: Building a Learnable Semantic Weighter"},{"level":4,"id":"1-3-a-joint-training-framework-for-downstream-awareness","text":"1.3 A Joint Training Framework for Downstream Awareness"},{"level":4,"id":"1-4-conclusion-2","text":"1.4 Conclusion"}];
  return (
    <div className="min-h-screen flex flex-col lg:flex-row">
      <LlmGuideNav currentRoute="10-surveys/c-ocr-d-ocr-2.0-dyj/aaai-fgd-motivation/aaai-fgd-motivation" />
      <main className="flex-1 min-w-0 px-6 pt-20 pb-12 lg:pt-12">
        <LlmGuideChapterBar currentRoute="10-surveys/c-ocr-d-ocr-2.0-dyj/aaai-fgd-motivation/aaai-fgd-motivation" />
        <header className="mb-12">
          <h1 className="text-3xl font-bold tracking-tight mb-2">AAAI风格的Motivation</h1>
          <p className="text-paper-800/50">{t("From LLM Guide", "来自 LLM 指南")}</p>
        </header>
        <article
          className="paper-content"
          dangerouslySetInnerHTML={{ __html: html }}
        />
      </main>
      <aside className="hidden lg:block w-64 shrink-0 sticky top-0 h-screen overflow-y-auto border-l border-paper-200 dark:border-slate-700 bg-paper-50 dark:bg-slate-900">
        <LlmGuideToc items={toc} />
      </aside>
    </div>
  );
}
